import { MindMap } from '../types/mindmap';
import { TEMPLATE_SVGS } from './templateIllustrations';

// ============================================================================
// 11. ROADMAP DE PRODUCTO IA GENERATIVA & AGENTES (Layout: Radial 360°)
// ============================================================================
export const AI_PRODUCT_ROADMAP_MAP: MindMap = {
  id: 'map-ai-roadmap',
  title: 'Roadmap de Producto IA Generativa & Agentes 2026',
  rootId: 'root',
  layout: 'radial',
  themeId: 'dark',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 52,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'ai-conn-1',
      fromId: 'ai-rag',
      toId: 'ai-eval',
      label: 'Evaluación RAG Triad',
      color: '#38bdf8',
      shape: 'bezier',
      curvature: -70,
      style: 'dashed',
      width: 2,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
    {
      id: 'ai-conn-2',
      fromId: 'ai-agents',
      toId: 'ai-tools',
      label: 'Invocación de Herramientas MCP',
      color: '#a855f7',
      shape: 'curved',
      curvature: 60,
      style: 'solid',
      width: 2.5,
      arrow: 'both',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'ai-conn-3',
      fromId: 'ai-guardrails',
      toId: 'ai-finetune',
      label: 'Alineación de Seguridad (RLHF)',
      color: '#f43f5e',
      shape: 'step',
      style: 'dotted',
      width: 2,
      arrow: 'end',
      opacity: 0.8,
      layer: 'below',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🤖 AI Agentic Architecture 2026',
      body: 'Ecosistema de modelos fundacionales, agentes autónomos, pipelines RAG híbridos e infraestructura MLOps',
      bodyFontSize: 11.5,
      bodyColor: '#94a3b8',
      parentId: null,
      children: ['ai-models', 'ai-agents', 'ai-rag', 'ai-infra', 'ai-safety', 'ai-ux'],
      side: 'root',
      shape: 'hexagon',
      color: '#0f172a',
      textColor: '#38bdf8',
      borderColor: '#0284c7',
      borderWidth: 2.5,
      bold: true,
      fontSize: 17,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.brainAi,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['IA', 'GenAI', 'Agentes'],
      cloud: {
        enabled: true,
        color: 'rgba(2, 132, 199, 0.12)',
        shape: 'round-rectangle',
      },
    },
    'ai-models': {
      id: 'ai-models',
      text: '🧠 Modelos & Enrutamiento',
      body: 'Selección dinámica y optimización de costes/latencia',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['ai-llm-router', 'ai-slm-edge', 'ai-finetune'],
      side: 'right',
      shape: 'oval',
      color: '#1e293b',
      textColor: '#f8fafc',
      borderColor: '#38bdf8',
      borderWidth: 2,
      bold: true,
    },
    'ai-llm-router': {
      id: 'ai-llm-router',
      text: 'Dynamic Model Router',
      body: 'Claude 3.7 / GPT-4o para razonamiento complejo, Flash para tareas rápidas',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'ai-models',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#e2e8f0',
      borderColor: '#0284c7',
    },
    'ai-slm-edge': {
      id: 'ai-slm-edge',
      text: 'Small Language Models (SLMs)',
      body: 'Modelos de 3B a 8B (Phi-4, Gemma 2) ejecutándose en local con WebGPU',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'ai-models',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#e2e8f0',
      borderColor: '#334155',
    },
    'ai-finetune': {
      id: 'ai-finetune',
      text: 'LoRA & DPO Fine-tuning',
      body: 'Adaptadores de bajo rango especializados en dominio corporativo',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'ai-models',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#e2e8f0',
      borderColor: '#334155',
    },
    'ai-agents': {
      id: 'ai-agents',
      text: '⚡ Multi-Agent System (MAS)',
      body: 'Orquestación de agentes con memoria y ejecución de herramientas',
      bodyFontSize: 10,
      bodyColor: '#e9d5ff',
      parentId: 'root',
      children: ['ai-planner', 'ai-memory', 'ai-tools'],
      side: 'right',
      shape: 'rectangle',
      color: '#581c87',
      textColor: '#f5d0fe',
      borderColor: '#c084fc',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.aiRobot,
      imagePosition: 'left',
      imageWidth: 40,
    },
    'ai-planner': {
      id: 'ai-planner',
      text: 'Planificación & ReAct Loop',
      body: 'Descomposición en sub-tareas, evaluación de resultados y autorreflexión',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-agents',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#a855f7',
    },
    'ai-memory': {
      id: 'ai-memory',
      text: 'Memoria Corto / Largo Plazo',
      body: 'Vector Stores + Semantic Cache + Resumen de grafo de conversación',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-agents',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#a855f7',
    },
    'ai-tools': {
      id: 'ai-tools',
      text: 'Herramientas MCP & APIs',
      body: 'Model Context Protocol: Acceso seguro a BDs, terminal, web search y Git',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-agents',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#f0abfc',
      borderColor: '#e879f9',
      bold: true,
    },
    'ai-rag': {
      id: 'ai-rag',
      text: '📚 RAG Híbrido Avanzado',
      body: 'Recuperación densa + dispersa (BM25) con reranking neuronal',
      bodyFontSize: 10,
      bodyColor: '#bae6fd',
      parentId: 'root',
      children: ['ai-chunking', 'ai-vector-db', 'ai-eval'],
      side: 'left',
      shape: 'square',
      color: '#0369a1',
      textColor: '#f0f9ff',
      borderColor: '#38bdf8',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.databaseCluster,
      imagePosition: 'left',
      imageWidth: 40,
    },
    'ai-chunking': {
      id: 'ai-chunking',
      text: 'Chunking Semántico & Jerárquico',
      body: 'División adaptativa por encabezados y relaciones padre-hijo',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-rag',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#38bdf8',
    },
    'ai-vector-db': {
      id: 'ai-vector-db',
      text: 'Vector Store & Embeddings',
      body: 'Qdrant / Milvus / pgvector con embeddings multilingües de 1536 dims',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-rag',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#38bdf8',
    },
    'ai-eval': {
      id: 'ai-eval',
      text: 'Evaluación Continua (Ragas)',
      body: 'Métricas de Faithfulness, Answer Relevance y Context Precision',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-rag',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#7dd3fc',
      borderColor: '#0284c7',
    },
    'ai-safety': {
      id: 'ai-safety',
      text: '🛡️ Seguridad & Guardrails',
      body: 'Mitigación de inyecciones de prompt y filtrado PII en tiempo real',
      bodyFontSize: 10,
      bodyColor: '#fecdd3',
      parentId: 'root',
      children: ['ai-guardrails', 'ai-audit'],
      side: 'left',
      shape: 'bubble',
      color: '#9f1239',
      textColor: '#fff1f2',
      borderColor: '#f43f5e',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.securityShield,
      imagePosition: 'left',
      imageWidth: 38,
    },
    'ai-guardrails': {
      id: 'ai-guardrails',
      text: 'NeMo Guardrails & Llama Guard',
      body: 'Comprobación bidireccional de entrada y salida contra jailbreaks',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-safety',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#f43f5e',
    },
    'ai-audit': {
      id: 'ai-audit',
      text: 'Observabilidad & Trazabilidad',
      body: 'Registro estructurado con Langfuse / Arize Phoenix para inspección',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'ai-safety',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#f43f5e',
    },
    'ai-infra': {
      id: 'ai-infra',
      text: '🚀 MLOps & Despliegue',
      body: 'Servidores vLLM, TensorRT-LLM y escalado elástico en Kubernetes',
      bodyFontSize: 10,
      bodyColor: '#bbf7d0',
      parentId: 'root',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#14532d',
      textColor: '#f0fdf4',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'ai-ux': {
      id: 'ai-ux',
      text: '✨ UX de IA Generativa',
      body: 'Streaming de tokens, visualización de razonamiento y citas verificables',
      bodyFontSize: 10,
      bodyColor: '#fef08a',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#713f12',
      textColor: '#fefce8',
      borderColor: '#eab308',
      borderWidth: 2,
      bold: true,
    },
  },
};

// ============================================================================
// 12. MATRIZ FODA / DAFO ESTRATÉGICO (Layout: Bilateral Cuadrantes)
// ============================================================================
export const SWOT_ANALYSIS_MAP: MindMap = {
  id: 'map-swot-matrix',
  title: 'Matriz Estratégica FODA / DAFO Corporativa',
  rootId: 'root',
  layout: 'standard',
  themeId: 'rainbow',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'swot-conn-1',
      fromId: 'foda-f1',
      toId: 'foda-o1',
      label: 'Estrategia FO: Maximizar',
      color: '#2563eb',
      shape: 'curved',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
    {
      id: 'swot-conn-2',
      fromId: 'foda-d1',
      toId: 'foda-a1',
      label: 'Estrategia DA: Mitigar Riesgo Crítico',
      color: '#dc2626',
      shape: 'bezier',
      curvature: 65,
      style: 'dashed',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '📊 Matriz FODA / DAFO',
      body: 'Diagnóstico estratégico 360° para toma de decisiones y ventajas competitivas',
      bodyFontSize: 11,
      bodyColor: '#334155',
      parentId: null,
      children: ['foda-strengths', 'foda-opportunities', 'foda-weaknesses', 'foda-threats'],
      side: 'root',
      shape: 'hexagon',
      color: '#f8fafc',
      textColor: '#0f172a',
      borderColor: '#64748b',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.swotMatrix,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Estrategia', 'FODA', 'Negocio'],
    },
    'foda-strengths': {
      id: 'foda-strengths',
      text: '💪 Fortalezas (Interno +)',
      body: 'Capacidades únicas, recursos propios y ventajas ya consolidadas',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['foda-f1', 'foda-f2', 'foda-f3'],
      side: 'right',
      shape: 'oval',
      color: '#dbeafe',
      textColor: '#1e3a8a',
      borderColor: '#3b82f6',
      borderWidth: 2.5,
      bold: true,
      cloud: { enabled: true, color: 'rgba(59, 130, 246, 0.08)', shape: 'round-rectangle' },
    },
    'foda-f1': {
      id: 'foda-f1',
      text: 'Tecnología Propietaria con Patente',
      body: 'Algoritmo con 40% menor consumo de memoria que competidores directos',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-strengths',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
    },
    'foda-f2': {
      id: 'foda-f2',
      text: 'Equipo Senior con Retención >95%',
      body: 'Cultura de alto desempeño y liderazgo consolidado en el sector',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-strengths',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
    },
    'foda-f3': {
      id: 'foda-f3',
      text: 'Solvencia Financiera & Flujo Positivo',
      body: 'Runway de 24 meses sin necesidad de deuda inmediata',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-strengths',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#eff6ff',
      textColor: '#1d4ed8',
      borderColor: '#60a5fa',
    },
    'foda-opportunities': {
      id: 'foda-opportunities',
      text: '🌟 Oportunidades (Externo +)',
      body: 'Tendencias de mercado, vacíos competitivos y nuevas normativas',
      bodyFontSize: 10,
      bodyColor: '#065f46',
      parentId: 'root',
      children: ['foda-o1', 'foda-o2', 'foda-o3'],
      side: 'right',
      shape: 'star',
      color: '#d1fae5',
      textColor: '#064e3b',
      borderColor: '#10b981',
      borderWidth: 2.5,
      bold: true,
      cloud: { enabled: true, color: 'rgba(16, 185, 129, 0.08)', shape: 'round-rectangle' },
    },
    'foda-o1': {
      id: 'foda-o1',
      text: 'Expansión a Mercado Latinoamericano',
      body: 'Crecimiento de demanda B2B superior al 65% interanual',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-opportunities',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#6ee7b7',
    },
    'foda-o2': {
      id: 'foda-o2',
      text: 'Alianzas Estratégicas con Integradores',
      body: 'Canal de distribución indirecto con más de 120 revendedores certificados',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-opportunities',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#6ee7b7',
    },
    'foda-o3': {
      id: 'foda-o3',
      text: 'Automatización con IA para Clientes',
      body: 'Monetización mediante suscripción a módulos avanzados de inteligencia artificial',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-opportunities',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#f0fdf4',
      textColor: '#047857',
      borderColor: '#34d399',
    },
    'foda-weaknesses': {
      id: 'foda-weaknesses',
      text: '⚠️ Debilidades (Interno -)',
      body: 'Limitaciones operativas, brechas técnicas o dependencia crítica',
      bodyFontSize: 10,
      bodyColor: '#92400e',
      parentId: 'root',
      children: ['foda-d1', 'foda-d2'],
      side: 'left',
      shape: 'fork',
      color: '#fef3c7',
      textColor: '#78350f',
      borderColor: '#f59e0b',
      borderWidth: 2.5,
      bold: true,
      cloud: { enabled: true, color: 'rgba(245, 158, 11, 0.08)', shape: 'round-rectangle' },
    },
    'foda-d1': {
      id: 'foda-d1',
      text: 'Proceso de Onboarding Complejo',
      body: 'Tiempo medio de implantación de 4 semanas, superior al promedio de 10 días',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-weaknesses',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fcd34d',
    },
    'foda-d2': {
      id: 'foda-d2',
      text: 'Baja Notoriedad de Marca Digital',
      body: 'Dependencia de ventas outbound sin tráfico orgánico consolidado',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-weaknesses',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fcd34d',
    },
    'foda-threats': {
      id: 'foda-threats',
      text: '🚨 Amenazas (Externo -)',
      body: 'Competencia agresiva, cambios legislativos o riesgos macroeconómicos',
      bodyFontSize: 10,
      bodyColor: '#991b1b',
      parentId: 'root',
      children: ['foda-a1', 'foda-a2'],
      side: 'left',
      shape: 'rectangle',
      color: '#fee2e2',
      textColor: '#7f1d1d',
      borderColor: '#ef4444',
      borderWidth: 2.5,
      bold: true,
      cloud: { enabled: true, color: 'rgba(239, 68, 68, 0.08)', shape: 'round-rectangle' },
    },
    'foda-a1': {
      id: 'foda-a1',
      text: 'Entrada de Competidores con Precios Low-Cost',
      body: 'Guerra de tarifas que erosiona los márgenes brutos tradicionales',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-threats',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fca5a5',
    },
    'foda-a2': {
      id: 'foda-a2',
      text: 'Nuevas Regulaciones de Privacidad (GDPR+)',
      body: 'Exigencia de auditorías de datos locales e infraestructura soberana',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'foda-threats',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#fff5f5',
      textColor: '#b91c1c',
      borderColor: '#f87171',
    },
  },
};

// ============================================================================
// 13. MARCO DE CIBERSEGURIDAD & ZERO TRUST (Layout: Organigrama Descendente NIST)
// ============================================================================
export const CYBERSECURITY_FRAMEWORK_MAP: MindMap = {
  id: 'map-cybersecurity-framework',
  title: 'Marco de Ciberseguridad NIST & Arquitectura Zero-Trust',
  rootId: 'root',
  layout: 'bottom',
  themeId: 'dark',
  edgeStyle: 'sharp',
  edgeProfile: 'uniform',
  edgeWidth: 2.5,
  edgeDash: 'solid',
  horizontalGap: 52,
  verticalGap: 14,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'sec-conn-1',
      fromId: 'sec-detect',
      toId: 'sec-respond',
      label: 'Respuesta Automática SOAR <60s',
      color: '#f43f5e',
      shape: 'bezier',
      curvature: -50,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'sec-conn-2',
      fromId: 'sec-backup',
      toId: 'sec-drp',
      label: 'RPO: 15 min / RTO: 1 hr',
      color: '#38bdf8',
      shape: 'curved',
      curvature: 45,
      style: 'dashed',
      width: 2,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🛡️ NIST Cybersecurity & Zero-Trust',
      body: 'Estrategia de defensa en profundidad: Nunca confíes, verifica siempre',
      bodyFontSize: 11.5,
      bodyColor: '#94a3b8',
      parentId: null,
      children: ['sec-id', 'sec-protect', 'sec-detect', 'sec-respond', 'sec-recover'],
      side: 'root',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#e0e7ff',
      borderColor: '#6366f1',
      borderWidth: 3,
      bold: true,
      fontSize: 17,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.securityShield,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Ciberseguridad', 'NIST', 'ZeroTrust'],
      cloud: { enabled: true, color: 'rgba(99, 102, 241, 0.1)', shape: 'round-rectangle' },
    },
    'sec-id': {
      id: 'sec-id',
      text: '1. IDENTIFY (Identificar)',
      body: 'Inventario de activos, análisis de riesgos y gobierno de datos',
      bodyFontSize: 10,
      bodyColor: '#e0e7ff',
      parentId: 'root',
      children: ['sec-assets', 'sec-vuln'],
      side: 'bottom',
      shape: 'bubble',
      color: '#312e81',
      textColor: '#e0e7ff',
      borderColor: '#818cf8',
      borderWidth: 2,
      bold: true,
    },
    'sec-assets': {
      id: 'sec-assets',
      text: 'Inventario Automatizado de Activos',
      body: 'Descubrimiento continuo de endpoints, instancias cloud y APIs expuestas',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-id',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#f8fafc',
      borderColor: '#4338ca',
    },
    'sec-vuln': {
      id: 'sec-vuln',
      text: 'Gestión Continua de Vulnerabilidades',
      body: 'Escaneo diario CVSS, dependencias SBOM y parches automatizados',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-id',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#a5b4fc',
      borderColor: '#6366f1',
    },
    'sec-protect': {
      id: 'sec-protect',
      text: '2. PROTECT (Proteger)',
      body: 'MFA biométrico, cifrado end-to-end y segmentación micro-red',
      bodyFontSize: 10,
      bodyColor: '#cffafe',
      parentId: 'root',
      children: ['sec-iam', 'sec-encrypt', 'sec-waf'],
      side: 'bottom',
      shape: 'bubble',
      color: '#164e63',
      textColor: '#cffafe',
      borderColor: '#06b6d4',
      borderWidth: 2,
      bold: true,
    },
    'sec-iam': {
      id: 'sec-iam',
      text: 'IAM con Principio de Menor Privilegio',
      body: 'Autenticación FIDO2 / Passkeys, RBAC estricto y sesiones Just-In-Time',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-protect',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#f8fafc',
      borderColor: '#0891b2',
    },
    'sec-encrypt': {
      id: 'sec-encrypt',
      text: 'Cifrado en Tránsito & Reposo',
      body: 'TLS 1.3 con HSTS + AES-256 GCM con gestión de llaves en HSM dedicado',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-protect',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#f8fafc',
      borderColor: '#0891b2',
    },
    'sec-waf': {
      id: 'sec-waf',
      text: 'WAF & Protección Anti-DDoS',
      body: 'Cloudflare / AWS Shield con reglas OWASP Top 10 y rate-limiting adaptativo',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-protect',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#67e8f9',
      borderColor: '#06b6d4',
    },
    'sec-detect': {
      id: 'sec-detect',
      text: '3. DETECT (Detectar)',
      body: 'SIEM centralizado, XDR en endpoints y análisis de comportamiento UEBA',
      bodyFontSize: 10,
      bodyColor: '#fef08a',
      parentId: 'root',
      children: ['sec-siem', 'sec-soc'],
      side: 'bottom',
      shape: 'bubble',
      color: '#713f12',
      textColor: '#fef08a',
      borderColor: '#eab308',
      borderWidth: 2,
      bold: true,
    },
    'sec-siem': {
      id: 'sec-siem',
      text: 'SIEM & Correlación en Tiempo Real',
      body: 'Ingesta de logs (Elastic / Splunk) con detección de anomalías con ML',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-detect',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#ca8a04',
    },
    'sec-soc': {
      id: 'sec-soc',
      text: 'SOC 24/7 & Threat Hunting',
      body: 'Monitorización proactiva de IOCs y ciberinteligencia MITRE ATT&CK',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-detect',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#fde047',
      borderColor: '#eab308',
    },
    'sec-respond': {
      id: 'sec-respond',
      text: '4. RESPOND (Responder)',
      body: 'Playbooks de contención automática, aislamiento y comunicación de crisis',
      bodyFontSize: 10,
      bodyColor: '#fecdd3',
      parentId: 'root',
      children: ['sec-soar'],
      side: 'bottom',
      shape: 'bubble',
      color: '#881337',
      textColor: '#ffe4e6',
      borderColor: '#f43f5e',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.bugFix,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'sec-soar': {
      id: 'sec-soar',
      text: 'Orquestación SOAR & Forense',
      body: 'Aislamiento de red automático de hosts infectados y volcado de memoria',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-respond',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#f43f5e',
    },
    'sec-recover': {
      id: 'sec-recover',
      text: '5. RECOVER (Recuperar)',
      body: 'Copias de seguridad inmutables, plan DRP y lecciones aprendidas',
      bodyFontSize: 10,
      bodyColor: '#bbf7d0',
      parentId: 'root',
      children: ['sec-backup', 'sec-drp'],
      side: 'bottom',
      shape: 'bubble',
      color: '#14532d',
      textColor: '#dcfce7',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'sec-backup': {
      id: 'sec-backup',
      text: 'Backups 3-2-1 Inmutables (Air-Gapped)',
      body: '3 copias, 2 soportes distintos, 1 fuera de línea protegida contra ransomware',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-recover',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#ffffff',
      borderColor: '#16a34a',
    },
    'sec-drp': {
      id: 'sec-drp',
      text: 'Disaster Recovery Plan (DRP)',
      body: 'Simulacros semestrales de restauración de servicios en región secundaria',
      bodyFontSize: 9.5,
      bodyColor: '#cbd5e1',
      parentId: 'sec-recover',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#86efac',
      borderColor: '#22c55e',
    },
  },
};

// ============================================================================
// 14. CUSTOMER JOURNEY MAP & EXPERIENCIA DE USUARIO (Layout: Unilateral Derecha)
// ============================================================================
export const CUSTOMER_JOURNEY_MAP: MindMap = {
  id: 'map-customer-journey',
  title: 'Mapa de Experiencia de Cliente (Customer Journey & UX)',
  rootId: 'root',
  layout: 'right',
  themeId: 'warm',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 54,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'cj-conn-1',
      fromId: 'cj-onboard',
      toId: 'cj-aha',
      label: 'Tiempo al Valor (TTV) < 5 min',
      color: '#ea580c',
      shape: 'bezier',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'cj-conn-2',
      fromId: 'cj-referral',
      toId: 'cj-discover',
      label: 'Bucle de Crecimiento Viral',
      color: '#059669',
      shape: 'curved',
      curvature: -120,
      style: 'dashed',
      width: 2.5,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🗺️ Customer Journey Map',
      body: 'Mapeo integral de puntos de contacto, emociones, fricciones y momentos de la verdad (Aha! Moments)',
      bodyFontSize: 11,
      bodyColor: '#7c2d12',
      parentId: null,
      children: ['cj-stage1', 'cj-stage2', 'cj-stage3', 'cj-stage4', 'cj-stage5'],
      side: 'root',
      shape: 'bubble',
      color: '#ffedd5',
      textColor: '#9a3412',
      borderColor: '#ea580c',
      borderWidth: 3,
      bold: true,
      fontSize: 17,
      imageUrl: TEMPLATE_SVGS.customerJourney,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['UX', 'CustomerJourney', 'Marketing'],
    },
    'cj-stage1': {
      id: 'cj-stage1',
      text: '1. Descubrimiento & Conciencia',
      body: 'El usuario identifica una necesidad y busca soluciones en el mercado',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['cj-discover', 'cj-content'],
      side: 'right',
      shape: 'bubble',
      color: '#fff7ed',
      textColor: '#c2410c',
      borderColor: '#fb923c',
      borderWidth: 2,
      bold: true,
    },
    'cj-discover': {
      id: 'cj-discover',
      text: 'Búsqueda Orgánica & Redes',
      body: 'Punto de contacto: Artículos de blog SEO y recomendaciones en LinkedIn',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage1',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fed7aa',
    },
    'cj-content': {
      id: 'cj-content',
      text: 'Emoción: Curiosidad & Interés',
      body: 'Fricción: Exceso de opciones en el mercado. Solución: Caso de estudio claro',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage1',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#fffbeb',
      textColor: '#b45309',
      borderColor: '#fcd34d',
    },
    'cj-stage2': {
      id: 'cj-stage2',
      text: '2. Evaluación & Comparativa',
      body: 'Análisis detallado de características, precios, reseñas y demostraciones',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['cj-demo', 'cj-trial'],
      side: 'right',
      shape: 'bubble',
      color: '#fff7ed',
      textColor: '#c2410c',
      borderColor: '#fb923c',
      borderWidth: 2,
      bold: true,
    },
    'cj-demo': {
      id: 'cj-demo',
      text: 'Prueba Gratuita sin Tarjeta',
      body: 'Registro en 1 clic con Google o GitHub para eliminar toda barrera inicial',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage2',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fed7aa',
    },
    'cj-trial': {
      id: 'cj-trial',
      text: 'Calculadora de ROI en Directo',
      body: 'Herramienta interactiva que cuantifica el ahorro en horas de trabajo',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage2',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#f0fdf4',
      textColor: '#15803d',
      borderColor: '#86efac',
    },
    'cj-stage3': {
      id: 'cj-stage3',
      text: '3. Compra & Activación (Onboarding)',
      body: 'El momento de la conversión y primera experiencia con el producto',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['cj-onboard', 'cj-aha'],
      side: 'right',
      shape: 'bubble',
      color: '#fef2f2',
      textColor: '#dc2626',
      borderColor: '#f87171',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.ecommerceCart,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'cj-onboard': {
      id: 'cj-onboard',
      text: 'Wizard de Configuración Guiada',
      body: '3 pasos simples para conectar datos y tener el primer resultado listo',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage3',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fca5a5',
    },
    'cj-aha': {
      id: 'cj-aha',
      text: '🎉 Momento Aha! (First Success)',
      body: 'El usuario exporta su primer informe en segundos. Sentimiento de satisfacción',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage3',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#fefce8',
      textColor: '#a16207',
      borderColor: '#fde047',
      bold: true,
    },
    'cj-stage4': {
      id: 'cj-stage4',
      text: '4. Retención & Uso Habitual',
      body: 'Integración en el flujo de trabajo diario y soporte proactivo',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['cj-success', 'cj-updates'],
      side: 'right',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#16a34a',
      borderColor: '#4ade80',
      borderWidth: 2,
      bold: true,
    },
    'cj-success': {
      id: 'cj-success',
      text: 'Customer Success & Check-in',
      body: 'Alertas automáticas si el usuario no inicia sesión en 7 días con tips útiles',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage4',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#bbf7d0',
    },
    'cj-updates': {
      id: 'cj-updates',
      text: 'Lanzamiento Semanal de Funciones',
      body: 'Changelog interactivo con feedback directo in-app',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage4',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ecfeff',
      textColor: '#0e7490',
      borderColor: '#67e8f9',
    },
    'cj-stage5': {
      id: 'cj-stage5',
      text: '5. Fidelización & Promoción (Advocacy)',
      body: 'Los clientes satisfechos se convierten en embajadores de la marca',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['cj-nps', 'cj-referral'],
      side: 'right',
      shape: 'bubble',
      color: '#faf5ff',
      textColor: '#9333ea',
      borderColor: '#c084fc',
      borderWidth: 2,
      bold: true,
    },
    'cj-nps': {
      id: 'cj-nps',
      text: 'Encuesta NPS (Score > 75)',
      body: 'Solicitud de reseña en G2 y Capterra a los promotores identificados',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage5',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#e9d5ff',
    },
    'cj-referral': {
      id: 'cj-referral',
      text: 'Programa de Referidos con Recompensa',
      body: 'Descuento del 20% recurrente por cada cliente invitado que contrate',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'cj-stage5',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#fdf2f8',
      textColor: '#be185d',
      borderColor: '#f472b6',
      bold: true,
    },
  },
};

// ============================================================================
// 15. ESTRUCTURA MAESTRA DE PITCH DECK PARA INVERSORES (Layout: Jerarquía Ascendente / Top)
// ============================================================================
export const STARTUP_PITCH_DECK_MAP: MindMap = {
  id: 'map-startup-pitch',
  title: 'Estructura Maestra de Pitch Deck para Inversores',
  rootId: 'root',
  layout: 'top',
  themeId: 'default',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'pitch-conn-1',
      fromId: 'p-solution',
      toId: 'p-traction',
      label: 'Product-Market Fit Validado',
      color: '#2563eb',
      shape: 'curved',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
    {
      id: 'pitch-conn-2',
      fromId: 'p-ask',
      toId: 'p-financials',
      label: 'Uso de Fondos: 18m Runway',
      color: '#059669',
      shape: 'bezier',
      curvature: 60,
      style: 'dashed',
      width: 2,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🚀 Seed / Series A Pitch Deck',
      body: 'Estructura probada de 10 diapositivas para levantar capital con fondos de Venture Capital',
      bodyFontSize: 11,
      bodyColor: '#dbeafe',
      parentId: null,
      children: ['p-problem', 'p-solution', 'p-market', 'p-business', 'p-traction', 'p-team', 'p-ask'],
      side: 'root',
      shape: 'bubble',
      color: '#1e3a8a',
      textColor: '#ffffff',
      borderColor: '#3b82f6',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.pitchDeck,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['PitchDeck', 'Startup', 'Inversión'],
    },
    'p-problem': {
      id: 'p-problem',
      text: '1. El Problema Urgente & Doloroso',
      body: 'Qué problema crítico sufre el cliente y cuánto dinero/tiempo pierde hoy',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#fee2e2',
      textColor: '#991b1b',
      borderColor: '#ef4444',
      borderWidth: 2,
      bold: true,
    },
    'p-solution': {
      id: 'p-solution',
      text: '2. Nuestra Solución & Propuesta Única',
      body: '10x más rápido, 50% más barato o con una experiencia radicalmente superior',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#dbeafe',
      textColor: '#1e40af',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
    },
    'p-market': {
      id: 'p-market',
      text: '3. Tamaño de Mercado (TAM, SAM, SOM)',
      body: 'TAM: $14B Global | SAM: $3.2B Europa/Latam | SOM: $180M año 3',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#fef3c7',
      textColor: '#92400e',
      borderColor: '#f59e0b',
      borderWidth: 2,
      bold: true,
    },
    'p-business': {
      id: 'p-business',
      text: '4. Modelo de Negocio & Unit Economics',
      body: 'SaaS B2B recurrente | LTV: $18,400 | CAC: $3,200 | Ratio LTV/CAC: 5.7x',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#dcfce7',
      textColor: '#166534',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'p-traction': {
      id: 'p-traction',
      text: '5. Tracción & Métricas Clave',
      body: '$1.4M ARR (+180% YoY) | Net Revenue Retention (NRR): 124% | 85 Clientes',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['p-financials'],
      side: 'top',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#15803d',
      borderColor: '#16a34a',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.financeGrowth,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'p-financials': {
      id: 'p-financials',
      text: 'Proyección a 3 Años',
      body: 'Año 1: $3.5M ARR | Año 2: $8.2M ARR | Año 3: $18M ARR con EBITDA positivo',
      bodyFontSize: 9,
      bodyColor: '#64748b',
      parentId: 'p-traction',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#047857',
      borderColor: '#86efac',
    },
    'p-team': {
      id: 'p-team',
      text: '6. Equipo Fundador & Ventaja Injusta',
      body: 'Fundadores con 2 exits previos en el sector y directores técnicos de FAANG',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#fdf4ff',
      textColor: '#86198f',
      borderColor: '#d946ef',
      borderWidth: 2,
      bold: true,
    },
    'p-ask': {
      id: 'p-ask',
      text: '7. Ronda de Inversión (The Ask)',
      body: 'Ronda Seed de $2.5M para escalar equipo comercial (50%) e ingeniería (35%)',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#fefce8',
      textColor: '#a16207',
      borderColor: '#eab308',
      borderWidth: 2.5,
      bold: true,
    },
  },
};

// ============================================================================
// 16. RUTA DE APRENDIZAJE FULLSTACK & DEVOPS (Layout: Ascendente / Top)
// ============================================================================
export const FULLSTACK_DEV_ROADMAP_MAP: MindMap = {
  id: 'map-fullstack-dev',
  title: 'Ruta de Carrera Desarrollador Fullstack & DevOps 2026',
  rootId: 'root',
  layout: 'top',
  themeId: 'dark',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 54,
  verticalGap: 15,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'fs-conn-1',
      fromId: 'fs-frontend',
      toId: 'fs-backend',
      label: 'Contratos tRPC / OpenAPI',
      color: '#38bdf8',
      shape: 'bezier',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'both',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'fs-conn-2',
      fromId: 'fs-backend',
      toId: 'fs-devops',
      label: 'CI/CD Pipeline Automatizado',
      color: '#a855f7',
      shape: 'curved',
      curvature: 50,
      style: 'dashed',
      width: 2,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '💻 Modern Fullstack & Cloud Native',
      body: 'Competencias esenciales para construir aplicaciones web escalables de grado de producción',
      bodyFontSize: 11,
      bodyColor: '#94a3b8',
      parentId: null,
      children: ['fs-frontend', 'fs-backend', 'fs-databases', 'fs-devops', 'fs-testing', 'fs-arch'],
      side: 'root',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#38bdf8',
      borderColor: '#0284c7',
      borderWidth: 3,
      bold: true,
      fontSize: 17,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.codeDev,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Programación', 'Fullstack', 'DevOps'],
    },
    'fs-frontend': {
      id: 'fs-frontend',
      text: '🎨 Frontend Moderno',
      body: 'React 19, Next.js App Router, TypeScript y Tailwind CSS / CSS Modules',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['fs-react', 'fs-state', 'fs-perf'],
      side: 'top',
      shape: 'bubble',
      color: '#1e293b',
      textColor: '#67e8f9',
      borderColor: '#06b6d4',
      borderWidth: 2,
      bold: true,
    },
    'fs-react': {
      id: 'fs-react',
      text: 'Server Components & Actions',
      body: 'Renderizado en servidor (RSC) para bundle cero en cliente y carga instantánea',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-frontend',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      borderColor: '#334155',
    },
    'fs-state': {
      id: 'fs-state',
      text: 'Gestión de Estado Ligera',
      body: 'Zustand para cliente + TanStack Query para sincronización de servidor y caché',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-frontend',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#a5f3fc',
      borderColor: '#0891b2',
    },
    'fs-perf': {
      id: 'fs-perf',
      text: 'Core Web Vitals & a11y',
      body: 'LCP < 1.2s, INP < 100ms, CLS = 0 y accesibilidad WCAG 2.1 AA',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-frontend',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      borderColor: '#334155',
    },
    'fs-backend': {
      id: 'fs-backend',
      text: '⚙️ Backend & APIs Escalables',
      body: 'Node.js / Bun con Fastify o Go / Rust para servicios de alta concurrencia',
      bodyFontSize: 10,
      bodyColor: '#e9d5ff',
      parentId: 'root',
      children: ['fs-apis', 'fs-auth'],
      side: 'top',
      shape: 'bubble',
      color: '#3b0764',
      textColor: '#f5d0fe',
      borderColor: '#c084fc',
      borderWidth: 2,
      bold: true,
    },
    'fs-apis': {
      id: 'fs-apis',
      text: 'Arquitectura de APIs',
      body: 'RESTful + gRPC para comunicación interna entre microservicios',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-backend',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      borderColor: '#334155',
    },
    'fs-auth': {
      id: 'fs-auth',
      text: 'Auth Segura (OAuth2 / JWT)',
      body: 'Auth.js / Supabase Auth con rotación de refresh tokens y cookies HttpOnly',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-backend',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#e879f9',
      borderColor: '#a855f7',
    },
    'fs-databases': {
      id: 'fs-databases',
      text: '🗄️ Persistencia & Bases de Datos',
      body: 'PostgreSQL como base principal + Redis para caché y Pub/Sub en memoria',
      bodyFontSize: 10,
      bodyColor: '#bae6fd',
      parentId: 'root',
      children: ['fs-postgres', 'fs-redis'],
      side: 'top',
      shape: 'bubble',
      color: '#0c4a6e',
      textColor: '#bae6fd',
      borderColor: '#38bdf8',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.databaseCluster,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'fs-postgres': {
      id: 'fs-postgres',
      text: 'PostgreSQL + Prisma / Drizzle',
      body: 'Migraciones controladas por código, tipos TypeScript estrictos e índices GiST/GIN',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-databases',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      borderColor: '#334155',
    },
    'fs-redis': {
      id: 'fs-redis',
      text: 'Redis / Dragonfly',
      body: 'Caché de consultas pesadas, colas con BullMQ y rate-limiting por IP',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-databases',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#7dd3fc',
      borderColor: '#0284c7',
    },
    'fs-devops': {
      id: 'fs-devops',
      text: '☁️ Cloud, Docker & CI/CD',
      body: 'Contenedores ligeros, GitHub Actions y despliegue en Kubernetes / AWS',
      bodyFontSize: 10,
      bodyColor: '#bbf7d0',
      parentId: 'root',
      children: ['fs-docker', 'fs-cicd'],
      side: 'top',
      shape: 'bubble',
      color: '#14532d',
      textColor: '#bbf7d0',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.cloudInfra,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'fs-docker': {
      id: 'fs-docker',
      text: 'Docker Multi-Stage Builds',
      body: 'Imágenes mínimas Alpine < 80MB optimizadas para producción',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-devops',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      borderColor: '#334155',
    },
    'fs-cicd': {
      id: 'fs-cicd',
      text: 'GitHub Actions Automatizado',
      body: 'Lint -> Typecheck -> Unit Tests -> E2E -> Build -> Despliegue en < 4 minutos',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'fs-devops',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#86efac',
      borderColor: '#16a34a',
    },
    'fs-testing': {
      id: 'fs-testing',
      text: '🧪 Testing Automatizado',
      body: 'Pirámide de pruebas: Vitest para unitarios + Playwright para E2E en navegadores reales',
      bodyFontSize: 10,
      bodyColor: '#fef08a',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#713f12',
      textColor: '#fefce8',
      borderColor: '#eab308',
      borderWidth: 2,
      bold: true,
    },
    'fs-arch': {
      id: 'fs-arch',
      text: '🏗️ Clean Architecture & DDD',
      body: 'Separación en capas de Dominio, Casos de Uso e Infraestructura desacoplada',
      bodyFontSize: 10,
      bodyColor: '#fecdd3',
      parentId: 'root',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#881337',
      textColor: '#fff1f2',
      borderColor: '#f43f5e',
      borderWidth: 2,
      bold: true,
    },
  },
};

// ============================================================================
// 17. PLAN FINANCIERO & CASH FLOW (Layout: Equilibrado Horizontal Arriba/Abajo)
// ============================================================================
export const FINANCIAL_BUDGET_MAP: MindMap = {
  id: 'map-financial-budget',
  title: 'Plan Financiero Corporativo, Presupuesto & Cash Flow',
  rootId: 'root',
  layout: 'balanced-horizontal',
  themeId: 'emerald',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'fin-conn-1',
      fromId: 'fin-rev-saas',
      toId: 'fin-opex-team',
      label: 'Margen Bruto del 82%',
      color: '#059669',
      shape: 'curved',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'fin-conn-2',
      fromId: 'fin-runway',
      toId: 'fin-capex',
      label: 'Límite de Inversión Trimestral',
      color: '#d97706',
      shape: 'bezier',
      curvature: 60,
      style: 'dashed',
      width: 2,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '💰 Presupuesto & Finanzas 2026',
      body: 'Planificación anual de ingresos, costes operativos, inversiones de capital y flujo de caja libre',
      bodyFontSize: 11,
      bodyColor: '#064e3b',
      parentId: null,
      children: ['fin-revenue', 'fin-cashflow', 'fin-opex', 'fin-capex'],
      side: 'root',
      shape: 'square',
      color: '#d1fae5',
      textColor: '#065f46',
      borderColor: '#10b981',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.financeGrowth,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Finanzas', 'Presupuesto', 'CashFlow'],
    },
    'fin-revenue': {
      id: 'fin-revenue',
      text: '📈 1. Fuentes de Ingresos ($4.8M)',
      body: 'Ventas recurrentes, expansión de cuentas y servicios profesionales',
      bodyFontSize: 10,
      bodyColor: '#166534',
      parentId: 'root',
      children: ['fin-rev-saas', 'fin-rev-enter', 'fin-rev-svc'],
      side: 'top',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#15803d',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'fin-rev-saas': {
      id: 'fin-rev-saas',
      text: 'Suscripciones SaaS Recurrentes ($3.4M)',
      body: '71% del total. 450 clientes SMB con ARPU de $630/mes',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-revenue',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#86efac',
    },
    'fin-rev-enter': {
      id: 'fin-rev-enter',
      text: 'Cuentas Enterprise Anuales ($1.1M)',
      body: '23% del total. 18 clientes corporativos con ACV de $61,000',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-revenue',
      children: [],
      side: 'top',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#86efac',
    },
    'fin-rev-svc': {
      id: 'fin-rev-svc',
      text: 'Servicios de Implementación ($300k)',
      body: '6% del total. Formación y migraciones personalizadas',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-revenue',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
    },
    'fin-cashflow': {
      id: 'fin-cashflow',
      text: '💵 2. Flujo de Caja & Runway',
      body: 'EBITDA: $1.28M (26.6% margen) | Caja disponible en banco: $2.4M',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['fin-runway'],
      side: 'top',
      shape: 'bubble',
      color: '#dbeafe',
      textColor: '#1d4ed8',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.analyticsPie,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'fin-runway': {
      id: 'fin-runway',
      text: 'Runway de Seguridad: > 28 Meses',
      body: 'Capacidad de soportar escenarios adversos de caída de ventas sin recortes',
      bodyFontSize: 9,
      bodyColor: '#64748b',
      parentId: 'fin-cashflow',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#1e40af',
      borderColor: '#93c5fd',
      bold: true,
    },
    'fin-opex': {
      id: 'fin-opex',
      text: '📉 3. Gastos Operativos OPEX ($3.1M)',
      body: 'Costes de personal, infraestructura cloud, marketing y herramientas',
      bodyFontSize: 10,
      bodyColor: '#991b1b',
      parentId: 'root',
      children: ['fin-opex-team', 'fin-opex-mkt', 'fin-opex-infra'],
      side: 'bottom',
      shape: 'bubble',
      color: '#fee2e2',
      textColor: '#b91c1c',
      borderColor: '#ef4444',
      borderWidth: 2,
      bold: true,
    },
    'fin-opex-team': {
      id: 'fin-opex-team',
      text: 'Salarios & Equipo ($1.9M)',
      body: '61% del OPEX. 24 personas a tiempo completo con seguridad social y beneficios',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-opex',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fca5a5',
    },
    'fin-opex-mkt': {
      id: 'fin-opex-mkt',
      text: 'Marketing & Adquisición ($720k)',
      body: '23% del OPEX. Google Ads, patrocinios de eventos y contenido',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-opex',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#fca5a5',
    },
    'fin-opex-infra': {
      id: 'fin-opex-infra',
      text: 'Servidores & Licencias ($480k)',
      body: '16% del OPEX. AWS, Snowflake, GitHub Enterprise y Slack',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'fin-opex',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#fff5f5',
      textColor: '#991b1b',
      borderColor: '#f87171',
    },
    'fin-capex': {
      id: 'fin-capex',
      text: '💼 4. Inversiones CAPEX ($420k)',
      body: 'Desarrollo de nuevas patentes y hardware de oficina central',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'bottom',
      shape: 'bubble',
      color: '#fef3c7',
      textColor: '#b45309',
      borderColor: '#f59e0b',
      borderWidth: 2,
      bold: true,
    },
  },
};

// ============================================================================
// 18. SISTEMA DE DISEÑO UI/UX & TOKENS (Layout: Radial 360°)
// ============================================================================
export const DESIGN_SYSTEM_MAP: MindMap = {
  id: 'map-design-system',
  title: 'Sistema de Diseño UI/UX & Tokens de Componentes',
  rootId: 'root',
  layout: 'radial',
  themeId: 'rainbow',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'ds-conn-1',
      fromId: 'ds-tokens',
      toId: 'ds-components',
      label: 'Propagación Automática a Figma & Código',
      color: '#d946ef',
      shape: 'bezier',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'ds-conn-2',
      fromId: 'ds-a11y',
      toId: 'ds-tokens-color',
      label: 'Ratio de Contraste WCAG AAA (7:1)',
      color: '#0284c7',
      shape: 'curved',
      curvature: 50,
      style: 'dashed',
      width: 2,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🎨 Aurora UI Design System',
      body: 'Lenguaje visual unificado, tokens de diseño semánticos, componentes accesibles y guías de interacción',
      bodyFontSize: 11,
      bodyColor: '#86198f',
      parentId: null,
      children: ['ds-tokens', 'ds-components', 'ds-patterns', 'ds-a11y'],
      side: 'root',
      shape: 'bubble',
      color: '#fdf4ff',
      textColor: '#a21caf',
      borderColor: '#d946ef',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.designPalette,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Diseño', 'DesignSystem', 'UI/UX'],
    },
    'ds-tokens': {
      id: 'ds-tokens',
      text: '1. Tokens Fundacionales',
      body: 'Variables primitivas y semánticas exportadas en JSON para React y Tailwind',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['ds-tokens-color', 'ds-tokens-type', 'ds-tokens-space'],
      side: 'right',
      shape: 'bubble',
      color: '#f5f3ff',
      textColor: '#6d28d9',
      borderColor: '#8b5cf6',
      borderWidth: 2,
      bold: true,
    },
    'ds-tokens-color': {
      id: 'ds-tokens-color',
      text: 'Paleta HSL & Modos Claro/Oscuro',
      body: 'Primary (Indigo), Neutral (Slate), Success (Emerald), Danger (Rose)',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-tokens',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#c4b5fd',
    },
    'ds-tokens-type': {
      id: 'ds-tokens-type',
      text: 'Escala Tipográfica (Inter / Plus Jakarta)',
      body: 'Modular scale 1.25 (Major Third) desde 12px (caption) hasta 48px (h1)',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-tokens',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#c4b5fd',
    },
    'ds-tokens-space': {
      id: 'ds-tokens-space',
      text: 'Espaciado & Cuadrícula de 4px/8px',
      body: 'Sistema de densidad adaptativa con radios de curvatura (sm: 6px, md: 12px, full: 9999px)',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-tokens',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#f5f3ff',
      textColor: '#5b21b6',
      borderColor: '#a78bfa',
    },
    'ds-components': {
      id: 'ds-components',
      text: '2. Biblioteca de Componentes',
      body: 'Componentes atómicos sin estilo (Radix UI) vestidos con nuestras clases',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: ['ds-cmp-buttons', 'ds-cmp-forms', 'ds-cmp-overlays'],
      side: 'right',
      shape: 'bubble',
      color: '#eff6ff',
      textColor: '#1d4ed8',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.mobileApp,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'ds-cmp-buttons': {
      id: 'ds-cmp-buttons',
      text: 'Botones & Acciones',
      body: 'Variantes: Primary, Secondary, Ghost, Danger con estados de carga (spinner) y foco visible',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-components',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
    },
    'ds-cmp-forms': {
      id: 'ds-cmp-forms',
      text: 'Formularios & Entradas',
      body: 'Inputs con validación flotante, selector de fechas accesible y combobox con autocompletado',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-components',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
    },
    'ds-cmp-overlays': {
      id: 'ds-cmp-overlays',
      text: 'Modales, Toasts & Tooltips',
      body: 'Gestión de portal, bloqueo de scroll de fondo y cierre con tecla ESC',
      bodyFontSize: 9.5,
      bodyColor: '#64748b',
      parentId: 'ds-components',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#eff6ff',
      textColor: '#1e40af',
      borderColor: '#60a5fa',
    },
    'ds-patterns': {
      id: 'ds-patterns',
      text: '3. Patrones de UX & Flujos',
      body: 'Estados vacíos ilustrados, esqueletos de carga (skeleton loaders) y mensajes de error',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#15803d',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'ds-a11y': {
      id: 'ds-a11y',
      text: '4. Accesibilidad (a11y WCAG 2.1)',
      body: 'Navegación completa por teclado (Tab/Flechas), atributos ARIA y soporte para lectores de pantalla',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ecfeff',
      textColor: '#0e7490',
      borderColor: '#06b6d4',
      borderWidth: 2,
      bold: true,
    },
  },
};

// ============================================================================
// 19. SISTEMA DE CREACIÓN DE CONTENIDO (Layout: Circular Concéntrico)
// ============================================================================
export const CONTENT_CREATOR_SYSTEM_MAP: MindMap = {
  id: 'map-content-creator',
  title: 'Sistema de Creación de Contenido Multimedia & Redes',
  rootId: 'root',
  layout: 'circular',
  themeId: 'warm',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'cc-conn-1',
      fromId: 'cc-pillar',
      toId: 'cc-repurpose',
      label: '1 Vídeo Largo = 15 Micro-contenidos',
      color: '#f43f5e',
      shape: 'bezier',
      curvature: -60,
      style: 'solid',
      width: 2.5,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'cc-conn-2',
      fromId: 'cc-newsletter',
      toId: 'cc-monetize',
      label: 'Conversión a Clientes de Pago',
      color: '#059669',
      shape: 'curved',
      curvature: 50,
      style: 'dashed',
      width: 2.5,
      arrow: 'both',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🎙️ Content Creator Machine',
      body: 'Fábrica de producción semanal: De una idea pilar a distribución omnicanal automatizada',
      bodyFontSize: 11,
      bodyColor: '#78350f',
      parentId: null,
      children: ['cc-ideation', 'cc-pillar', 'cc-repurpose', 'cc-newsletter', 'cc-monetize'],
      side: 'root',
      shape: 'star',
      color: '#fef3c7',
      textColor: '#92400e',
      borderColor: '#f59e0b',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.podcastMic,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Contenido', 'YouTube', 'Podcast', 'Marketing'],
    },
    'cc-ideation': {
      id: 'cc-ideation',
      text: '1. Ideación & Validación de Temas',
      body: 'Análisis de tendencias en YouTube, preguntas frecuentes de la comunidad y Google Trends',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#1e293b',
      borderColor: '#cbd5e1',
      borderWidth: 1.5,
      bold: true,
    },
    'cc-pillar': {
      id: 'cc-pillar',
      text: '2. Contenido Pilar (YouTube / Podcast)',
      body: 'Episodio profundo de 25-40 min con guion estructurado en ganchos, desarrollo y llamada a la acción',
      bodyFontSize: 10,
      bodyColor: '#991b1b',
      parentId: 'root',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#fee2e2',
      textColor: '#b91c1c',
      borderColor: '#ef4444',
      borderWidth: 2,
      bold: true,
    },
    'cc-repurpose': {
      id: 'cc-repurpose',
      text: '3. Reciclaje (Shorts / Reels / TikTok)',
      body: 'Extracción de los 5 momentos más virales con subtítulos dinámicos y formatos verticales',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#dbeafe',
      textColor: '#1d4ed8',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.gamificationTrophy,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'cc-newsletter': {
      id: 'cc-newsletter',
      text: '4. Newsletter Semanal (Substack)',
      body: 'Resumen ejecutivo con valor accionable enviado cada jueves a 22,000 suscriptores',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#15803d',
      borderColor: '#22c55e',
      borderWidth: 2,
      bold: true,
    },
    'cc-monetize': {
      id: 'cc-monetize',
      text: '5. Vías de Monetización',
      body: 'Patrocinios directos, cursos avanzados de pago y membresía privada de comunidad',
      bodyFontSize: 9.5,
      bodyColor: '#701a75',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#fdf4ff',
      textColor: '#a21caf',
      borderColor: '#d946ef',
      borderWidth: 2,
      bold: true,
    },
  },
};

// ============================================================================
// 20. PLAN INTEGRAL DE SALUD & BIOHACKING (Layout: Circular Concéntrico)
// ============================================================================
export const HEALTH_WELLNESS_MAP: MindMap = {
  id: 'map-health-wellness',
  title: 'Plan Integral de Salud, Hábitos & Biohacking',
  rootId: 'root',
  layout: 'circular',
  themeId: 'emerald',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'hw-conn-1',
      fromId: 'hw-sleep',
      toId: 'hw-mind',
      label: 'Recuperación del Sistema Nervioso',
      color: '#0284c7',
      shape: 'curved',
      curvature: -55,
      style: 'solid',
      width: 2.5,
      arrow: 'both',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'hw-conn-2',
      fromId: 'hw-exercise',
      toId: 'hw-nutrition',
      label: 'Síntesis Proteica & Recuperación Muscular',
      color: '#16a34a',
      shape: 'bezier',
      curvature: 60,
      style: 'dashed',
      width: 2.5,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🌱 Longevidad & Alto Rendimiento',
      body: 'Protocolo holístico basado en ciencia: Optimización de sueño, nutrición celular, ejercicio y claridad mental',
      bodyFontSize: 11,
      bodyColor: '#064e3b',
      parentId: null,
      children: ['hw-sleep', 'hw-nutrition', 'hw-exercise', 'hw-mind'],
      side: 'root',
      shape: 'bubble',
      color: '#dcfce7',
      textColor: '#14532d',
      borderColor: '#22c55e',
      borderWidth: 3,
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      imageUrl: TEMPLATE_SVGS.healthHeart,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Salud', 'Hábitos', 'Bienestar', 'Biohacking'],
    },
    'hw-sleep': {
      id: 'hw-sleep',
      text: '😴 1. Higiene del Sueño (8 Horas)',
      body: 'Horario constante de descanso, habitación a 18°C y bloqueo de luz azul 90 min antes',
      bodyFontSize: 10,
      bodyColor: '#1e3a8a',
      parentId: 'root',
      children: ['hw-circadian'],
      side: 'right',
      shape: 'bubble',
      color: '#dbeafe',
      textColor: '#1e40af',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
    },
    'hw-circadian': {
      id: 'hw-circadian',
      text: 'Luz Solar Matutina (15 min)',
      body: 'Anclaje del ritmo circadiano y activación natural de cortisol al despertar',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'hw-sleep',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#1d4ed8',
      borderColor: '#93c5fd',
    },
    'hw-nutrition': {
      id: 'hw-nutrition',
      text: '🥗 2. Nutrición & Hidratación',
      body: 'Comida real sin ultraprocesados, 1.8g proteína/kg y 3 litros de agua con electrolitos',
      bodyFontSize: 10,
      bodyColor: '#14532d',
      parentId: 'root',
      children: ['hw-fasting'],
      side: 'right',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#166534',
      borderColor: '#16a34a',
      borderWidth: 2,
      bold: true,
      imageUrl: TEMPLATE_SVGS.sustainabilityLeaf,
      imagePosition: 'left',
      imageWidth: 36,
    },
    'hw-fasting': {
      id: 'hw-fasting',
      text: 'Ventana de Ayuno 14/10',
      body: 'Favorece la autofagia celular y descanso del sistema digestivo durante la noche',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'hw-nutrition',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#15803d',
      borderColor: '#86efac',
    },
    'hw-exercise': {
      id: 'hw-exercise',
      text: '🏋️ 3. Entrenamiento Físico Mixto',
      body: 'Fuerza 4x/semana + 150 min de cardio Zona 2 + 1 sesión de alta intensidad (VO2 Max)',
      bodyFontSize: 10,
      bodyColor: '#78350f',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#fef3c7',
      textColor: '#92400e',
      borderColor: '#f59e0b',
      borderWidth: 2,
      bold: true,
    },
    'hw-mind': {
      id: 'hw-mind',
      text: '🧘 4. Gestión del Estrés & Mente',
      body: 'Meditación mindfulness 10 min, escritura de gratitud y pausas de respiración fisiológica',
      bodyFontSize: 10,
      bodyColor: '#701a75',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#fdf4ff',
      textColor: '#86198f',
      borderColor: '#d946ef',
      borderWidth: 2,
      bold: true,
    },
  },
};
