import { MindMap } from '../types/mindmap';
import { TEMPLATE_SVGS } from './templateIllustrations';
import {
  AI_PRODUCT_ROADMAP_MAP,
  SWOT_ANALYSIS_MAP,
  CYBERSECURITY_FRAMEWORK_MAP,
  CUSTOMER_JOURNEY_MAP,
  STARTUP_PITCH_DECK_MAP,
  FULLSTACK_DEV_ROADMAP_MAP,
  FINANCIAL_BUDGET_MAP,
  DESIGN_SYSTEM_MAP,
  CONTENT_CREATOR_SYSTEM_MAP,
  HEALTH_WELLNESS_MAP,
} from './additionalTemplates';

export {
  AI_PRODUCT_ROADMAP_MAP,
  SWOT_ANALYSIS_MAP,
  CYBERSECURITY_FRAMEWORK_MAP,
  CUSTOMER_JOURNEY_MAP,
  STARTUP_PITCH_DECK_MAP,
  FULLSTACK_DEV_ROADMAP_MAP,
  FINANCIAL_BUDGET_MAP,
  DESIGN_SYSTEM_MAP,
  CONTENT_CREATOR_SYSTEM_MAP,
  HEALTH_WELLNESS_MAP,
};

// ============================================================================
// 1. GUÍA INTERACTIVA & TUTORIAL COMPLETO (Bilateral Orgánico / Buzan Style)
// ============================================================================
export const TUTORIAL_MAP: MindMap = {
  id: 'map-tutorial-freeplane',
  title: 'FreeMind Studio - Guía Interactiva',
  rootId: 'root',
  layout: 'standard',
  themeId: 'default',
  backgroundColor: '#f8fafc',
  backgroundPattern: 'hexagons',
  backgroundPatternColor: '#cbd5e1',
  backgroundPatternSize: 22,
  backgroundPatternOpacity: 0.35,
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.5,
  edgeDash: 'solid',
  horizontalGap: 56,
  verticalGap: 14,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-1',
      fromId: 'exp-mm',
      toId: 'off-privacy',
      label: '100% Compatible & Seguro',
      color: '#3b82f6',
      shape: 'bezier',
      curvature: -55,
      style: 'dashed',
      width: 2,
      arrow: 'end',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'conn-2',
      fromId: 'sc-outline',
      toId: 'view-outline',
      label: 'Acceso Directo (Alt+O)',
      color: '#8b5cf6',
      shape: 'curved',
      curvature: 50,
      style: 'solid',
      width: 2.5,
      arrow: 'both',
      opacity: 0.95,
      layer: 'above',
    },
    {
      id: 'conn-3',
      fromId: 'feat-notes',
      toId: 'exp-html',
      label: 'Exportable con formato',
      color: '#10b981',
      shape: 'bezier',
      curvature: -45,
      style: 'dashed',
      width: 2,
      arrow: 'end',
      opacity: 0.9,
      layer: 'above',
    },
    {
      id: 'conn-4',
      fromId: 'fmt-pill',
      toId: 'feat-tags',
      label: 'Etiquetas visuales',
      color: '#ec4899',
      shape: 'step',
      style: 'dotted',
      width: 2,
      arrow: 'end',
      opacity: 0.85,
      layer: 'below',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🧠 FreeMind Map Studio',
      body: 'Aplicación moderna, portable y 100% offline para organizar ideas con la potencia de Freeplane y la fluidez visual de Mindomo',
      bodyFontSize: 12,
      bodyColor: '#dbeafe',
      bodyItalic: true,
      bodyAlign: 'center',
      parentId: null,
      children: [
        'node-shortcuts',
        'node-styles',
        'node-enrichment',
        'node-export',
        'node-views',
        'node-offline',
      ],
      side: 'root',
      shape: 'bubble',
      color: '#1d4ed8',
      textColor: '#ffffff',
      bold: true,
      fontSize: 18,
      textAlign: 'center',
      borderColor: '#3b82f6',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.brainAi,
      imagePosition: 'top',
      imageWidth: 64,
      note: '# Bienvenido a FreeMind Map Studio\n\nEsta es una aplicación **offline, moderna y portable** diseñada con las mejores características de **Freeplane** y **Mindomo**.\n\n### Principales Beneficios:\n- ⚡ **Rápida y fluida**: Edición 100% con teclado o ratón.\n- 🔒 **Privacidad Total**: No requiere internet ni cuentas. Tus mapas se guardan localmente.\n- 📁 **Compatibilidad Universal**: Importa y exporta archivos nativos `.mm` de Freeplane / FreeMind, páginas HTML autónomas, imágenes PNG/SVG y Markdown.',
      icons: ['sparkles'],
      tags: ['Tutorial', 'FreeMind'],
    },
    'node-shortcuts': {
      id: 'node-shortcuts',
      text: '⚡ Atajos de Teclado',
      body: 'Control total de creación y edición ágil a la velocidad del pensamiento',
      bodyFontSize: 11,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['sc-child', 'sc-sibling', 'sc-fold', 'sc-edit', 'sc-outline', 'sc-props'],
      side: 'right',
      shape: 'bubble',
      color: '#eff6ff',
      textColor: '#1e3a8a',
      borderColor: '#3b82f6',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
      tags: ['Teclado', 'Atajos'],
      cloud: {
        enabled: true,
        color: 'rgba(59, 130, 246, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'sc-child': {
      id: 'sc-child',
      text: 'TAB o INSERT',
      body: 'Crea de inmediato un nuevo sub-nodo hijo en el siguiente nivel',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#2563eb',
      bold: true,
      borderColor: '#93c5fd',
      borderWidth: 1.5,
      icons: ['zap'],
    },
    'sc-sibling': {
      id: 'sc-sibling',
      text: 'ENTER',
      body: 'Inserta un nuevo nodo hermano al mismo nivel jerárquico',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#2563eb',
      bold: true,
      borderColor: '#93c5fd',
      borderWidth: 1.5,
    },
    'sc-fold': {
      id: 'sc-fold',
      text: 'ESPACIO: Plegar / Desplegar',
      body: 'Oculta o expande ramas secundarias mostrando el contador',
      bodyFontSize: 10,
      bodyColor: '#b45309',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#fffbeb',
      textColor: '#92400e',
      bold: true,
      borderColor: '#f59e0b',
      borderWidth: 1.5,
      icons: ['sparkles'],
    },
    'sc-edit': {
      id: 'sc-edit',
      text: 'F2 o Doble Clic',
      body: 'Edición rápida directa del texto del nodo',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#1e293b',
    },
    'sc-outline': {
      id: 'sc-outline',
      text: 'ALT + O: Panel de Esquema',
      body: 'Alterna vista estructurada tipo documento',
      bodyFontSize: 10,
      bodyColor: '#581c87',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'oval',
      color: '#f5f3ff',
      textColor: '#6d28d9',
      bold: true,
      borderColor: '#c4b5fd',
      borderWidth: 1.5,
      icons: ['layout'],
    },
    'sc-props': {
      id: 'sc-props',
      text: 'ALT + P: Panel de Propiedades',
      body: 'Configura colores, formas, enlaces y espaciados',
      bodyFontSize: 10,
      bodyColor: '#0369a1',
      parentId: 'node-shortcuts',
      children: [],
      side: 'right',
      shape: 'oval',
      color: '#f0f9ff',
      textColor: '#0284c7',
      bold: true,
      borderColor: '#7dd3fc',
      borderWidth: 1.5,
      icons: ['sliders'],
    },
    'node-styles': {
      id: 'node-styles',
      text: '🎨 10 Formas y Estilos Visuales',
      body: 'Geometrías poligonales SVG, degradados, tramas y dimensiones adaptativas',
      bodyFontSize: 11,
      bodyColor: '#6b21a8',
      parentId: 'root',
      children: [
        'fmt-bubble',
        'fmt-fork',
        'fmt-rect',
        'fmt-square',
        'fmt-oval',
        'fmt-circle',
        'fmt-pill',
        'fmt-hex',
        'fmt-arrow',
        'fmt-star',
      ],
      side: 'right',
      shape: 'bubble',
      color: '#faf5ff',
      textColor: '#581c87',
      borderColor: '#a855f7',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
      tags: ['Estilos', '10 Formas', 'Degradados'],
      cloud: {
        enabled: true,
        color: 'rgba(168, 85, 247, 0.08)',
        shape: 'arc',
      },
    },
    'fmt-bubble': {
      id: 'fmt-bubble',
      text: 'Burbuja (Bubble)',
      body: 'Caja con esquinas suaves y fondo sólido moderno',
      bodyFontSize: 10,
      bodyColor: '#86198f',
      bodyItalic: true,
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#fdf4ff',
      textColor: '#86198f',
      borderColor: '#f0abfc',
      borderWidth: 1.5,
      bold: true,
    },
    'fmt-fork': {
      id: 'fmt-fork',
      text: 'Horquilla Clásica (Fork)',
      body: 'Estilo tradicional Freeplane con línea de apoyo inferior',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#1e293b',
      bold: true,
    },
    'fmt-rect': {
      id: 'fmt-rect',
      text: 'Rectángulo Estructurado',
      body: 'Bordes rectos diseñados para diagramas y procesos técnicos',
      bodyFontSize: 10,
      bodyColor: '#334155',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#f8fafc',
      textColor: '#0f172a',
      borderWidth: 1.5,
      borderColor: '#94a3b8',
    },
    'fmt-square': {
      id: 'fmt-square',
      text: 'Cuadrada (1:1)',
      body: 'Proporción simétrica para bloques y tarjetas fijas',
      bodyFontSize: 10,
      bodyColor: '#1e3a8a',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'square',
      customWidth: 110,
      customHeight: 110,
      color: '#eff6ff',
      textColor: '#1d4ed8',
      borderColor: '#3b82f6',
      borderWidth: 2,
      borderDash: 'solid',
      bold: true,
    },
    'fmt-oval': {
      id: 'fmt-oval',
      text: 'Óvalo Suave',
      body: 'Curvatura elíptica armónica con borde discontinuo',
      bodyFontSize: 10,
      bodyColor: '#065f46',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'oval',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#10b981',
      borderWidth: 2,
      borderDash: 'dashed',
      bold: true,
    },
    'fmt-circle': {
      id: 'fmt-circle',
      text: 'Circular (1:1)',
      body: 'Degradado radial y simetría perfecta',
      bodyFontSize: 9.5,
      bodyColor: '#ffffff',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'circle',
      customWidth: 115,
      customHeight: 115,
      bgType: 'gradient',
      gradientColor1: '#8b5cf6',
      gradientColor2: '#ec4899',
      gradientDirection: 'to-br',
      textColor: '#ffffff',
      borderColor: '#ffffff',
      borderWidth: 2,
      bold: true,
    },
    'fmt-pill': {
      id: 'fmt-pill',
      text: 'Cápsula / Pill Tag',
      body: 'Formato compacto con bordes 100% redondeados',
      bodyFontSize: 10,
      bodyColor: '#9d174d',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#fdf2f8',
      textColor: '#be185d',
      borderColor: '#f472b6',
      borderWidth: 1.5,
      bold: true,
    },
    'fmt-hex': {
      id: 'fmt-hex',
      text: 'Hexágono Angular',
      body: 'Contorno SVG nítido y fondo con textura de trama',
      bodyFontSize: 10,
      bodyColor: '#92400e',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'hexagon',
      bgType: 'pattern',
      color: '#fef3c7',
      nodePattern: 'hexagons',
      nodePatternColor: '#d97706',
      nodePatternSize: 14,
      nodePatternOpacity: 0.35,
      textColor: '#78350f',
      borderColor: '#d97706',
      borderWidth: 2,
      bold: true,
    },
    'fmt-arrow': {
      id: 'fmt-arrow',
      text: 'Flecha de Dirección',
      body: 'Flujo de proceso con degradado oceánico y punta angular',
      bodyFontSize: 10,
      bodyColor: '#ffffff',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'arrow',
      bgType: 'gradient',
      gradientColor1: '#0284c7',
      gradientColor2: '#06b6d4',
      gradientDirection: 'to-r',
      textColor: '#ffffff',
      borderColor: '#38bdf8',
      borderWidth: 2,
      bold: true,
    },
    'fmt-star': {
      id: 'fmt-star',
      text: 'Estrella de 5 Puntas',
      body: 'Destacados y metas clave con altura estilizada',
      bodyFontSize: 9.5,
      bodyColor: '#78350f',
      parentId: 'node-styles',
      children: [],
      side: 'right',
      shape: 'star',
      color: '#fef9c3',
      textColor: '#854d0e',
      borderColor: '#eab308',
      borderWidth: 2,
      bold: true,
    },
    'node-enrichment': {
      id: 'node-enrichment',
      text: '💎 Enriquecimiento de Nodos',
      body: 'Añade notas Markdown, etiquetas, iconos y barras de progreso',
      bodyFontSize: 11,
      bodyColor: '#047857',
      parentId: 'root',
      children: ['feat-notes', 'feat-tags', 'feat-progress', 'feat-icons'],
      side: 'right',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#065f46',
      borderColor: '#10b981',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
    },
    'feat-notes': {
      id: 'feat-notes',
      text: 'Notas Extensas en Markdown',
      body: 'Documentos completos con listas y títulos integrados',
      bodyFontSize: 10,
      bodyColor: '#047857',
      parentId: 'node-enrichment',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#047857',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      note: '### Soporte Markdown Total\n\n- Títulos H1-H3\n- **Texto en Negrita** y *Cursiva*\n- Listas de tareas y código',
      icons: ['bookmark'],
      tags: ['Markdown', 'Documentos'],
    },
    'feat-tags': {
      id: 'feat-tags',
      text: 'Etiquetas & Tags',
      body: 'Clasificación por colores y filtrado dinámico',
      bodyFontSize: 10,
      bodyColor: '#065f46',
      parentId: 'node-enrichment',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      tags: ['Importante', 'Feature'],
    },
    'feat-progress': {
      id: 'feat-progress',
      text: 'Seguimiento de Progreso',
      body: 'Barras de completitud visuales de 0% a 100%',
      bodyFontSize: 10,
      bodyColor: '#047857',
      parentId: 'node-enrichment',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#047857',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      progress: 75,
      icons: ['trophy'],
      tags: ['Progreso', 'Tareas'],
    },
    'feat-icons': {
      id: 'feat-icons',
      text: 'Iconos con Color & Escala',
      body: 'Personaliza tinte, tamaño de 10px a 36px y propaga a ramas hijas o hermanas',
      bodyFontSize: 10,
      bodyColor: '#047857',
      parentId: 'node-enrichment',
      children: [],
      side: 'right',
      shape: 'oval',
      color: '#ffffff',
      textColor: '#047857',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      icons: ['sparkles', 'star', 'zap', 'target', 'heart'],
      iconColor: '#10b981',
      iconSize: 16,
    },
    'node-export': {
      id: 'node-export',
      text: '📁 Exportación & Compatibilidad',
      body: 'Soporte universal sin depender de la nube ni formatos propietarios',
      bodyFontSize: 11,
      bodyColor: '#c2410c',
      parentId: 'root',
      children: ['exp-mm', 'exp-html', 'exp-img', 'exp-md'],
      side: 'left',
      shape: 'bubble',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#f97316',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
      tags: ['Exportación', 'Formatos'],
      cloud: {
        enabled: true,
        color: 'rgba(249, 115, 22, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'exp-mm': {
      id: 'exp-mm',
      text: 'Freeplane / FreeMind (.mm)',
      body: 'Importa y exporta archivos XML nativos compatibles',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'node-export',
      children: [],
      side: 'left',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#ea580c',
      borderColor: '#fed7aa',
      borderWidth: 1.5,
      bold: true,
      icons: ['sparkles'],
    },
    'exp-html': {
      id: 'exp-html',
      text: 'Página Web Autónoma (HTML)',
      body: 'Archivo HTML único interactivo que abre en cualquier navegador',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'node-export',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#ea580c',
      borderColor: '#fed7aa',
      borderWidth: 1.5,
    },
    'exp-img': {
      id: 'exp-img',
      text: 'Imágenes Vectoriales (PNG / SVG)',
      body: 'Exportación de alta resolución lista para presentaciones',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'node-export',
      children: [],
      side: 'left',
      shape: 'oval',
      color: '#ffffff',
      textColor: '#ea580c',
      borderColor: '#fed7aa',
      borderWidth: 1.5,
    },
    'exp-md': {
      id: 'exp-md',
      text: 'Documento Markdown (.md)',
      body: 'Estructura en lista anidada con encabezados y notas',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'node-export',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#ea580c',
      borderColor: '#fed7aa',
      borderWidth: 1.5,
    },
    'node-views': {
      id: 'node-views',
      text: '👁️ Modos de Vista & Presentación',
      body: 'Presentación en 3 modos, 6 distribuciones de diseño y panel plegable',
      bodyFontSize: 11,
      bodyColor: '#4338ca',
      parentId: 'root',
      children: [
        'view-outline',
        'view-presentation',
        'view-layouts',
        'view-filter',
      ],
      side: 'left',
      shape: 'bubble',
      color: '#eef2ff',
      textColor: '#3730a3',
      borderColor: '#6366f1',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
    },
    'view-outline': {
      id: 'view-outline',
      text: 'Modo Esquema (Alt+O)',
      body: 'Vista de texto estructurado editable por niveles y jerarquías',
      bodyFontSize: 10,
      bodyColor: '#3730a3',
      parentId: 'node-views',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#4f46e5',
      borderColor: '#c7d2fe',
      borderWidth: 1.5,
    },
    'view-presentation': {
      id: 'view-presentation',
      text: '3 Modos de Presentación (F5)',
      body: 'Clásico (diapositivas por rama), Elaborado y Dinámico',
      bodyFontSize: 10,
      bodyColor: '#3730a3',
      parentId: 'node-views',
      children: [],
      side: 'left',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#4f46e5',
      borderColor: '#818cf8',
      borderWidth: 2,
      icons: ['rocket'],
    },
    'view-layouts': {
      id: 'view-layouts',
      text: '6 Distribuciones del Mapa',
      body: 'Bilateral, Izquierda, Derecha, Radial 360°, Vertical Arriba y Abajo',
      bodyFontSize: 10,
      bodyColor: '#3730a3',
      parentId: 'node-views',
      children: [],
      side: 'left',
      shape: 'oval',
      color: '#ffffff',
      textColor: '#4f46e5',
      borderColor: '#c7d2fe',
      borderWidth: 1.5,
      icons: ['layout'],
    },
    'view-filter': {
      id: 'view-filter',
      text: 'Búsqueda & Filtro (Ctrl+F)',
      body: 'Filtra nodos por texto, etiquetas o estado en tiempo real',
      bodyFontSize: 10,
      bodyColor: '#3730a3',
      parentId: 'node-views',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#4f46e5',
      borderColor: '#c7d2fe',
      borderWidth: 1.5,
      icons: ['search'],
    },
    'node-offline': {
      id: 'node-offline',
      text: '🔒 Privacidad & Filosofía Offline',
      body: 'Tus ideas nunca salen de tu ordenador ni se envían a servidores',
      bodyFontSize: 11,
      bodyColor: '#0f766e',
      parentId: 'root',
      children: ['off-privacy', 'off-portable'],
      side: 'left',
      shape: 'bubble',
      color: '#f0fdfa',
      textColor: '#115e59',
      borderColor: '#14b8a6',
      borderWidth: 2,
      bold: true,
      fontSize: 15,
      tags: ['Offline', 'Privacidad'],
    },
    'off-privacy': {
      id: 'off-privacy',
      text: 'Almacenamiento Local Seguro',
      body: 'Persistencia directa en tu navegador vía IndexedDB/LocalStorage',
      bodyFontSize: 10,
      bodyColor: '#115e59',
      parentId: 'node-offline',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#0d9488',
      borderColor: '#99f6e4',
      borderWidth: 1.5,
      icons: ['check'],
    },
    'off-portable': {
      id: 'off-portable',
      text: 'Portable y Sin Instalación',
      body: 'Funciona como app autónoma lista para llevar en un pendrive',
      bodyFontSize: 10,
      bodyColor: '#115e59',
      parentId: 'node-offline',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#ffffff',
      textColor: '#0d9488',
      borderColor: '#99f6e4',
      borderWidth: 1.5,
      icons: ['zap'],
    },
  },
};

// ============================================================================
// 2. PLANIFICACIÓN ESTRATÉGICA & OKRs 2026 (Árbol a la Derecha / Warm Sunset)
// ============================================================================
export const OKR_STRATEGY_MAP: MindMap = {
  id: 'map-okr-strategy-2026',
  title: 'Plan Estratégico & OKRs Anuales',
  rootId: 'root',
  layout: 'right',
  themeId: 'sunset',
  backgroundColor: '#fffbeb',
  backgroundPattern: 'squares',
  backgroundPatternColor: '#fde68a',
  backgroundPatternSize: 20,
  backgroundPatternOpacity: 0.4,
  edgeStyle: 'sharp',
  edgeProfile: 'spindle',
  edgeWidth: 2.8,
  edgeDash: 'solid',
  horizontalGap: 72,
  verticalGap: 18,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-okr-1',
      fromId: 'kr-retention',
      toId: 'kr-cac',
      label: 'Impacto directo en Unit Economics',
      color: '#ea580c',
      style: 'dashed',
      arrow: 'end',
    },
    {
      id: 'conn-okr-2',
      fromId: 'kr-infra',
      toId: 'kr-expansion',
      label: 'Habilitador técnico',
      color: '#d97706',
      style: 'solid',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🎯 Estrategia & OKRs 2026',
      body: 'Crecimiento sostenible, excelencia operativa y fidelización de clientes',
      bodyFontSize: 12,
      bodyColor: '#ffedd5',
      parentId: null,
      children: ['obj-growth', 'obj-product', 'obj-ops'],
      side: 'root',
      shape: 'rectangle',
      color: '#c2410c',
      textColor: '#ffffff',
      bold: true,
      fontSize: 17,
      borderColor: '#ea580c',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.strategyChess,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['target'],
      tags: ['Estrategia', 'OKRs'],
    },
    'obj-growth': {
      id: 'obj-growth',
      text: 'Obj 1: Expansión de Mercado & ARR',
      body: 'Alcanzar $5M ARR con márgenes positivos',
      bodyFontSize: 11,
      bodyColor: '#7c2d12',
      parentId: 'root',
      children: ['kr-expansion', 'kr-cac', 'kr-retention'],
      side: 'right',
      shape: 'rectangle',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#fb923c',
      borderWidth: 2,
      bold: true,
      progress: 60,
      cloud: {
        enabled: true,
        color: 'rgba(234, 88, 12, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'kr-expansion': {
      id: 'kr-expansion',
      text: 'KR 1.1: Apertura en 3 nuevos países',
      body: 'Lanzamiento localizado en México, Colombia y Chile',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'obj-growth',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      progress: 66,
      tags: ['Q1-Q2'],
    },
    'kr-cac': {
      id: 'kr-cac',
      text: 'KR 1.2: Reducción CAC en 25%',
      body: 'Optimización de canales orgánicos y referidos',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'obj-growth',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      progress: 40,
      tags: ['Growth'],
    },
    'kr-retention': {
      id: 'kr-retention',
      text: 'KR 1.3: Net Revenue Retention > 115%',
      body: 'Upselling de planes Pro y reducción de churn mensual < 1.2%',
      bodyFontSize: 10,
      bodyColor: '#9a3412',
      parentId: 'obj-growth',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      progress: 75,
      icons: ['trophy'],
      tags: ['Retención', 'SaaS'],
    },
    'obj-product': {
      id: 'obj-product',
      text: 'Obj 2: Experiencia de Usuario & IA',
      body: 'Liderar en velocidad y capacidades asistidas por IA generativa',
      bodyFontSize: 11,
      bodyColor: '#831843',
      parentId: 'root',
      children: ['kr-speed', 'kr-ai-assist', 'kr-nps'],
      side: 'right',
      shape: 'rectangle',
      color: '#fff1f2',
      textColor: '#9f1239',
      borderColor: '#f43f5e',
      borderWidth: 2,
      bold: true,
      progress: 45,
    },
    'kr-speed': {
      id: 'kr-speed',
      text: 'KR 2.1: Tiempo de carga < 300ms',
      body: 'Optimización de renderizado Canvas y bundles ligeros',
      bodyFontSize: 10,
      bodyColor: '#9f1239',
      parentId: 'obj-product',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#be123c',
      borderColor: '#fecdd3',
      borderWidth: 1.5,
      progress: 80,
      icons: ['zap'],
      tags: ['Performance', 'Frontend'],
    },
    'kr-ai-assist': {
      id: 'kr-ai-assist',
      text: 'KR 2.2: Generador de mapas mentales asistido',
      body: 'Transformación de texto y notas en ramas estructuradas',
      bodyFontSize: 10,
      bodyColor: '#9f1239',
      parentId: 'obj-product',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#be123c',
      borderColor: '#fecdd3',
      borderWidth: 1.5,
      progress: 30,
      icons: ['sparkles'],
      tags: ['IA', 'Generativo'],
    },
    'kr-nps': {
      id: 'kr-nps',
      text: 'KR 2.3: NPS superior a 65 puntos',
      body: 'Encuestas in-app y entrevistas de satisfacción',
      bodyFontSize: 10,
      bodyColor: '#9f1239',
      parentId: 'obj-product',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#be123c',
      borderColor: '#fecdd3',
      borderWidth: 1.5,
      progress: 50,
    },
    'obj-ops': {
      id: 'obj-ops',
      text: 'Obj 3: Excelencia Operacional & Infra',
      body: 'Disponibilidad 99.99% y procesos de QA automatizados',
      bodyFontSize: 11,
      bodyColor: '#78350f',
      parentId: 'root',
      children: ['kr-infra', 'kr-security'],
      side: 'right',
      shape: 'rectangle',
      color: '#fffbeb',
      textColor: '#92400e',
      borderColor: '#f59e0b',
      borderWidth: 2,
      bold: true,
      progress: 70,
    },
    'kr-infra': {
      id: 'kr-infra',
      text: 'KR 3.1: Pipeline CI/CD con test coverage > 85%',
      body: 'Despliegues automatizados sin downtime',
      bodyFontSize: 10,
      bodyColor: '#92400e',
      parentId: 'obj-ops',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#b45309',
      borderColor: '#fde68a',
      borderWidth: 1.5,
      progress: 90,
      icons: ['check'],
      tags: ['DevOps', 'CI/CD'],
    },
    'kr-security': {
      id: 'kr-security',
      text: 'KR 3.2: Certificación SOC2 & ISO 27001',
      body: 'Auditorías de seguridad e infraestructura blindada',
      bodyFontSize: 10,
      bodyColor: '#92400e',
      parentId: 'obj-ops',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#b45309',
      borderColor: '#fde68a',
      borderWidth: 1.5,
      progress: 50,
      tags: ['Seguridad', 'SOC2'],
    },
  },
};

// ============================================================================
// 3. ARQUITECTURA DE SOFTWARE & CLOUD (Modo Oscuro / Hexágonos & Dashed)
// ============================================================================
export const CLOUD_ARCH_MAP: MindMap = {
  id: 'map-cloud-microservices',
  title: 'Arquitectura Cloud Microservicios',
  rootId: 'root',
  layout: 'radial',
  themeId: 'dark',
  edgeStyle: 'linear',
  edgeProfile: 'uniform',
  edgeWidth: 2.0,
  edgeDash: 'dashed',
  horizontalGap: 80,
  verticalGap: 14,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-arch-1',
      fromId: 'srv-auth',
      toId: 'db-users',
      label: 'gRPC / TLS Seguro',
      color: '#38bdf8',
      style: 'solid',
      arrow: 'end',
    },
    {
      id: 'conn-arch-2',
      fromId: 'srv-orders',
      toId: 'msg-kafka',
      label: 'Event Streaming (Pub/Sub)',
      color: '#a78bfa',
      style: 'dashed',
      arrow: 'both',
    },
    {
      id: 'conn-arch-3',
      fromId: 'msg-kafka',
      toId: 'srv-notifications',
      label: 'Consumer Group',
      color: '#34d399',
      style: 'dashed',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '⚡ Cloud Platform Core',
      body: 'Malla distribuida en Kubernetes con balanceo global y almacenamiento multi-región',
      bodyFontSize: 11,
      bodyColor: '#94a3b8',
      parentId: null,
      children: ['gateway-layer', 'services-layer', 'data-layer', 'obs-layer'],
      side: 'root',
      shape: 'hexagon',
      color: '#1e293b',
      textColor: '#38bdf8',
      bold: true,
      fontSize: 16,
      borderColor: '#38bdf8',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.cloudInfra,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['sparkles'],
      tags: ['Cloud', 'Kubernetes'],
    },
    'gateway-layer': {
      id: 'gateway-layer',
      text: '🌐 API Gateway & Edge',
      body: 'Cloudflare CDN, WAF, SSL Termination y Rate Limiting',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['gw-auth', 'gw-routing', 'gw-rate'],
      side: 'left',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#60a5fa',
      borderColor: '#3b82f6',
      borderWidth: 1.5,
      bold: true,
    },
    'gw-auth': {
      id: 'gw-auth',
      text: 'JWT & OAuth2 Validator',
      body: 'Validación stateless en el borde sin tocar el backend',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'gateway-layer',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#93c5fd',
      borderColor: '#1d4ed8',
      borderWidth: 1,
    },
    'gw-routing': {
      id: 'gw-routing',
      text: 'Dynamic Reverse Proxy',
      body: 'Enrutamiento por versión v1/v2 y Canary releases',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'gateway-layer',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#93c5fd',
      borderColor: '#1d4ed8',
      borderWidth: 1,
    },
    'gw-rate': {
      id: 'gw-rate',
      text: 'Redis Token Bucket',
      body: 'Protección contra abusos: 1000 req/min por API Key',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'gateway-layer',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#93c5fd',
      borderColor: '#1d4ed8',
      borderWidth: 1,
    },
    'services-layer': {
      id: 'services-layer',
      text: '⚙️ Servicios Backend',
      body: 'Contenedores Docker escalados horizontalmente en EKS',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['srv-auth', 'srv-orders', 'srv-notifications'],
      side: 'right',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#a78bfa',
      borderColor: '#8b5cf6',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(139, 92, 246, 0.12)',
        shape: 'round-rectangle',
      },
    },
    'srv-auth': {
      id: 'srv-auth',
      text: 'Auth & Identity Service (Go)',
      body: 'Manejo de tokens, 2FA y permisos RBAC',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'services-layer',
      children: [],
      side: 'right',
      shape: 'hexagon',
      color: '#1e293b',
      textColor: '#c4b5fd',
      borderColor: '#6d28d9',
      borderWidth: 1.5,
      icons: ['zap'],
    },
    'srv-orders': {
      id: 'srv-orders',
      text: 'Orders & Checkout (Node.js)',
      body: 'Transacciones atómicas y pagos con Stripe',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'services-layer',
      children: [],
      side: 'right',
      shape: 'hexagon',
      color: '#1e293b',
      textColor: '#c4b5fd',
      borderColor: '#6d28d9',
      borderWidth: 1.5,
    },
    'srv-notifications': {
      id: 'srv-notifications',
      text: 'Notification Worker (Rust)',
      body: 'Envío de emails y notificaciones push en segundo plano',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'services-layer',
      children: [],
      side: 'right',
      shape: 'hexagon',
      color: '#1e293b',
      textColor: '#c4b5fd',
      borderColor: '#6d28d9',
      borderWidth: 1.5,
    },
    'data-layer': {
      id: 'data-layer',
      text: '💾 Persistencia & Mensajería',
      body: 'Bases de datos replicadas y broker de eventos asíncronos',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['db-users', 'msg-kafka', 'cache-redis'],
      side: 'right',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#34d399',
      borderColor: '#10b981',
      borderWidth: 1.5,
      bold: true,
    },
    'db-users': {
      id: 'db-users',
      text: 'PostgreSQL Aurora (Multi-AZ)',
      body: 'ACID compliance con réplicas de lectura automáticas',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'data-layer',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#6ee7b7',
      borderColor: '#059669',
      borderWidth: 1,
    },
    'msg-kafka': {
      id: 'msg-kafka',
      text: 'Apache Kafka Event Bus',
      body: 'Topics particionados con retención de 7 días',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'data-layer',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#6ee7b7',
      borderColor: '#059669',
      borderWidth: 1,
    },
    'cache-redis': {
      id: 'cache-redis',
      text: 'Redis Cluster In-Memory',
      body: 'Cache de sesiones y tablas calientes con TTL de 1 hora',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'data-layer',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#6ee7b7',
      borderColor: '#059669',
      borderWidth: 1,
    },
    'obs-layer': {
      id: 'obs-layer',
      text: '📊 Observabilidad & Logs',
      body: 'Telemetría OpenTelemetry, métricas Prometheus y trazas Grafana Tempo',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['obs-metrics', 'obs-tracing'],
      side: 'left',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#fbbf24',
      borderColor: '#f59e0b',
      borderWidth: 1.5,
      bold: true,
    },
    'obs-metrics': {
      id: 'obs-metrics',
      text: 'Prometheus & Grafana Alertas',
      body: 'Monitoreo de latencia p99, CPU y consumo de memoria',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'obs-layer',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#fde68a',
      borderColor: '#b45309',
      borderWidth: 1,
    },
    'obs-tracing': {
      id: 'obs-tracing',
      text: 'Distributed Tracing Jaeger',
      body: 'Rastreo correlacionado de peticiones a través de microservicios',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'obs-layer',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#1e293b',
      textColor: '#fde68a',
      borderColor: '#b45309',
      borderWidth: 1,
    },
  },
};

// ============================================================================
// 4. LLUVIA DE IDEAS & BRAINSTORMING (Arcoíris / Curvas Fluídas / Hourglass)
// ============================================================================
export const BRAINSTORMING_MAP: MindMap = {
  id: 'map-creative-brainstorm',
  title: 'Brainstorming Creativo & Nuevos Productos',
  rootId: 'root',
  layout: 'standard',
  themeId: 'rainbow',
  edgeStyle: 'bezier',
  edgeProfile: 'hourglass',
  edgeWidth: 4.0,
  edgeDash: 'solid',
  horizontalGap: 48,
  verticalGap: 20,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-bs-1',
      fromId: 'idea-ai-sketch',
      toId: 'idea-gamify',
      label: 'Sinergia para Engagement',
      color: '#ec4899',
      style: 'solid',
      arrow: 'both',
    },
    {
      id: 'conn-bs-2',
      fromId: 'idea-templates-market',
      toId: 'mkt-viral-tiktok',
      label: 'Estrategia de Difusión',
      color: '#8b5cf6',
      style: 'dashed',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '💡 Lluvia de Ideas 2026',
      body: 'Innovaciones de producto, viralidad y monetización comunitaria',
      bodyFontSize: 12,
      bodyColor: '#f1f5f9',
      parentId: null,
      children: ['cat-features', 'cat-growth', 'cat-community', 'cat-monetization'],
      side: 'root',
      shape: 'bubble',
      color: '#0f172a',
      textColor: '#ffffff',
      bold: true,
      fontSize: 18,
      borderColor: '#ec4899',
      borderWidth: 3,
      imageUrl: TEMPLATE_SVGS.ideaBulb,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['sparkles'],
      tags: ['Brainstorming', 'Ideas'],
    },
    'cat-features': {
      id: 'cat-features',
      text: '🚀 Nuevas Funcionalidades',
      body: 'Ideas para enriquecer la experiencia de mapeo mental',
      bodyFontSize: 10.5,
      bodyColor: '#9f1239',
      parentId: 'root',
      children: ['idea-ai-sketch', 'idea-audio-notes', 'idea-gamify'],
      side: 'right',
      shape: 'oval',
      color: '#ffe4e6',
      textColor: '#9f1239',
      borderColor: '#f43f5e',
      borderWidth: 2,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(244, 63, 94, 0.1)',
        shape: 'arc',
      },
    },
    'idea-ai-sketch': {
      id: 'idea-ai-sketch',
      text: 'Auto-Diagramado Inteligente',
      body: 'Convierte bocetos hechos a mano en nodos vectoriales limpios',
      bodyFontSize: 10,
      bodyColor: '#881337',
      parentId: 'cat-features',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#e11d48',
      borderColor: '#fda4af',
      borderWidth: 1.5,
      icons: ['sparkles'],
      tags: ['Top Vote ⭐', 'Prioridad'],
    },
    'idea-audio-notes': {
      id: 'idea-audio-notes',
      text: 'Notas de Voz Transcritas',
      body: 'Graba ideas al paso y ordénalas automáticamente en el mapa',
      bodyFontSize: 10,
      bodyColor: '#881337',
      parentId: 'cat-features',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#e11d48',
      borderColor: '#fda4af',
      borderWidth: 1.5,
      tags: ['Audio', 'Productividad'],
    },
    'idea-gamify': {
      id: 'idea-gamify',
      text: 'Rachas de Estudio & Gamificación',
      body: 'Medallas al completar mapas mentales y repasar exámenes',
      bodyFontSize: 10,
      bodyColor: '#881337',
      parentId: 'cat-features',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#e11d48',
      borderColor: '#fda4af',
      borderWidth: 1.5,
      icons: ['trophy'],
    },
    'cat-growth': {
      id: 'cat-growth',
      text: '📣 Viralidad & Marketing',
      body: 'Tácticas de difusión orgánica y alianzas educativas',
      bodyFontSize: 10.5,
      bodyColor: '#581c87',
      parentId: 'root',
      children: ['mkt-viral-tiktok', 'mkt-edu-partner'],
      side: 'right',
      shape: 'oval',
      color: '#f3e8ff',
      textColor: '#6b21a8',
      borderColor: '#a855f7',
      borderWidth: 2,
      bold: true,
    },
    'mkt-viral-tiktok': {
      id: 'mkt-viral-tiktok',
      text: 'Plantillas Estéticas para TikTok/Reels',
      body: 'Tutoriales visuales "Cómo organizo mi semestre con mapas"',
      bodyFontSize: 10,
      bodyColor: '#4c1d95',
      parentId: 'cat-growth',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#7e22ce',
      borderColor: '#d8b4fe',
      borderWidth: 1.5,
      icons: ['rocket'],
    },
    'mkt-edu-partner': {
      id: 'mkt-edu-partner',
      text: 'Alianzas con Universidades',
      body: 'Talleres gratuitos de técnicas de estudio estructurado',
      bodyFontSize: 10,
      bodyColor: '#4c1d95',
      parentId: 'cat-growth',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#7e22ce',
      borderColor: '#d8b4fe',
      borderWidth: 1.5,
    },
    'cat-community': {
      id: 'cat-community',
      text: '👥 Comunidad & Colaboración',
      body: 'Crear un ecosistema donde los usuarios compartan sus mapas',
      bodyFontSize: 10.5,
      bodyColor: '#065f46',
      parentId: 'root',
      children: ['idea-templates-market', 'idea-challenges'],
      side: 'left',
      shape: 'oval',
      color: '#d1fae5',
      textColor: '#047857',
      borderColor: '#10b981',
      borderWidth: 2,
      bold: true,
    },
    'idea-templates-market': {
      id: 'idea-templates-market',
      text: 'Galería Abierta de Plantillas',
      body: 'Usuarios destacados pueden publicar mapas sobre medicina, leyes y finanzas',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'cat-community',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      icons: ['bookmark'],
    },
    'idea-challenges': {
      id: 'idea-challenges',
      text: 'Retos Mensuales de Productividad',
      body: 'Eventos en vivo para estructurar libros en mapas mentales en 1 hora',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'cat-community',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
    },
    'cat-monetization': {
      id: 'cat-monetization',
      text: '💰 Vías de Monetización',
      body: 'Modelos de negocio sostenibles respetando la privacidad',
      bodyFontSize: 10.5,
      bodyColor: '#78350f',
      parentId: 'root',
      children: ['mon-pro-license', 'mon-teams'],
      side: 'left',
      shape: 'oval',
      color: '#fef3c7',
      textColor: '#b45309',
      borderColor: '#f59e0b',
      borderWidth: 2,
      bold: true,
    },
    'mon-pro-license': {
      id: 'mon-pro-license',
      text: 'Licencia Lifetime "Paga Una Vez"',
      body: 'Acceso a exportación avanzada SVG/PDF ultra HD sin suscripciones',
      bodyFontSize: 10,
      bodyColor: '#78350f',
      parentId: 'cat-monetization',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#d97706',
      borderColor: '#fde68a',
      borderWidth: 1.5,
      icons: ['check'],
    },
    'mon-teams': {
      id: 'mon-teams',
      text: 'Workspace para Equipos & P2P Sync',
      body: 'Sincronización cifrada de extremo a extremo para empresas',
      bodyFontSize: 10,
      bodyColor: '#78350f',
      parentId: 'cat-monetization',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#d97706',
      borderColor: '#fde68a',
      borderWidth: 1.5,
    },
  },
};

// ============================================================================
// 5. ORGANIGRAMA CORPORATIVO & EQUIPOS (Minimal Mono / Ángulos Rectos Sharp)
// ============================================================================
export const ORG_CHART_MAP: MindMap = {
  id: 'map-org-chart-corp',
  title: 'Organigrama y Estructura de Equipo',
  rootId: 'root',
  layout: 'bottom',
  themeId: 'minimal',
  edgeStyle: 'sharp',
  edgeProfile: 'uniform',
  edgeWidth: 1.8,
  edgeDash: 'solid',
  horizontalGap: 64,
  verticalGap: 10,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-org-1',
      fromId: 'lead-qa',
      toId: 'lead-dev',
      label: 'Reporte de Calidad & Triage',
      color: '#52525b',
      style: 'dashed',
      arrow: 'both',
    },
    {
      id: 'conn-org-2',
      fromId: 'lead-growth',
      toId: 'lead-design',
      label: 'A/B Testing & UI Assets',
      color: '#71717a',
      style: 'solid',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🏢 Dirección General (CEO)',
      body: 'Liderazgo ejecutivo, visión estratégica y gobierno corporativo',
      bodyFontSize: 11,
      bodyColor: '#e4e4e7',
      parentId: null,
      children: ['dept-tech', 'dept-product', 'dept-ops'],
      side: 'root',
      shape: 'rectangle',
      color: '#18181b',
      textColor: '#ffffff',
      bold: true,
      fontSize: 16,
      borderColor: '#27272a',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.teamCollab,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Dirección', 'C-Level'],
    },
    'dept-tech': {
      id: 'dept-tech',
      text: 'VP de Ingeniería (CTO)',
      body: 'Responsable de la infraestructura, seguridad y desarrollo técnico',
      bodyFontSize: 10,
      bodyColor: '#52525b',
      parentId: 'root',
      children: ['lead-dev', 'lead-infra', 'lead-qa'],
      side: 'right',
      shape: 'rectangle',
      color: '#f4f4f5',
      textColor: '#18181b',
      borderColor: '#a1a1aa',
      borderWidth: 1.5,
      bold: true,
      tags: ['Ingeniería', 'Tech'],
    },
    'lead-dev': {
      id: 'lead-dev',
      text: 'Tech Lead Full-Stack',
      body: 'Equipo Frontend (React/TS) y Backend distribuido',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-tech',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'lead-infra': {
      id: 'lead-infra',
      text: 'Líder DevOps & Cloud',
      body: 'Kubernetes, monitoreo y seguridad perimetral',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-tech',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'lead-qa': {
      id: 'lead-qa',
      text: 'Líder QA & Automatización',
      body: 'Pruebas E2E, rendimiento y regresiones',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-tech',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'dept-product': {
      id: 'dept-product',
      text: 'VP de Producto (CPO)',
      body: 'Estrategia de producto, diseño de experiencia e investigación',
      bodyFontSize: 10,
      bodyColor: '#52525b',
      parentId: 'root',
      children: ['lead-design', 'lead-pm'],
      side: 'right',
      shape: 'rectangle',
      color: '#f4f4f5',
      textColor: '#18181b',
      borderColor: '#a1a1aa',
      borderWidth: 1.5,
      bold: true,
    },
    'lead-design': {
      id: 'lead-design',
      text: 'Head of Product Design (UI/UX)',
      body: 'Sistema de diseño, accesibilidad y prototipado',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-product',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'lead-pm': {
      id: 'lead-pm',
      text: 'Product Managers (Core & Growth)',
      body: 'Roadmap, priorización de backlog y discovery con clientes',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-product',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'dept-ops': {
      id: 'dept-ops',
      text: 'VP de Operaciones & Finanzas (COO)',
      body: 'Gestión financiera, talento humano y cumplimiento legal',
      bodyFontSize: 10,
      bodyColor: '#52525b',
      parentId: 'root',
      children: ['lead-hr', 'lead-growth'],
      side: 'right',
      shape: 'rectangle',
      color: '#f4f4f5',
      textColor: '#18181b',
      borderColor: '#a1a1aa',
      borderWidth: 1.5,
      bold: true,
    },
    'lead-hr': {
      id: 'lead-hr',
      text: 'People & Culture Manager',
      body: 'Atracción de talento, clima laboral y capacitación continua',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-ops',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
    'lead-growth': {
      id: 'lead-growth',
      text: 'Head of Growth Marketing',
      body: 'Captación de usuarios, analítica y canales de conversión',
      bodyFontSize: 9.5,
      bodyColor: '#71717a',
      parentId: 'dept-ops',
      children: [],
      side: 'right',
      shape: 'rectangle',
      color: '#ffffff',
      textColor: '#27272a',
      borderColor: '#d4d4d8',
      borderWidth: 1,
    },
  },
};

// ============================================================================
// 6. SPRINT AGILE & SCRUM TRACKER (Bosque Esmeralda / Trazos Dotted & Pills)
// ============================================================================
export const AGILE_SPRINT_MAP: MindMap = {
  id: 'map-agile-sprint-scrum',
  title: 'Tablero Sprint Scrum & Backlog',
  rootId: 'root',
  layout: 'balanced-horizontal',
  themeId: 'forest',
  edgeStyle: 'bezier',
  edgeProfile: 'tapered',
  edgeWidth: 3.0,
  edgeDash: 'dotted',
  horizontalGap: 60,
  verticalGap: 16,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-agile-1',
      fromId: 'task-auth-oauth',
      toId: 'task-canvas-export',
      label: 'Bloqueante para release',
      color: '#059669',
      style: 'dashed',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🏃 Sprint 42 (Release v2.4)',
      body: 'Meta del Sprint: Exportador vectorial de alto rendimiento y atajos personalizados',
      bodyFontSize: 11.5,
      bodyColor: '#d1fae5',
      parentId: null,
      children: ['col-backlog', 'col-progress', 'col-review', 'col-done'],
      side: 'root',
      shape: 'pill',
      color: '#065f46',
      textColor: '#ffffff',
      bold: true,
      fontSize: 16,
      borderColor: '#10b981',
      borderWidth: 2,
      progress: 68,
      imageUrl: TEMPLATE_SVGS.agileKanban,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['rocket'],
      tags: ['Scrum', 'Sprint-42'],
    },
    'col-progress': {
      id: 'col-progress',
      text: '⚡ En Desarrollo (In Progress)',
      body: 'Tareas activas asignadas a desarrolladores',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['task-canvas-export', 'task-shortcuts'],
      side: 'top',
      shape: 'bubble',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(16, 185, 129, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'task-canvas-export': {
      id: 'task-canvas-export',
      text: 'Exportador SVG con estilos incrustados',
      body: 'Asegurar que las fuentes personalizadas y perfiles de grosor se rendericen en el vector',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-progress',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 70,
      tags: ['Frontend', '8 SP'],
    },
    'task-shortcuts': {
      id: 'task-shortcuts',
      text: 'Editor modal de atajos de teclado',
      body: 'Permitir reasignar teclas tipo Vim o estilo Freeplane clásico',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-progress',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 45,
      tags: ['UX', 'Atajos'],
    },
    'col-review': {
      id: 'col-review',
      text: '🔍 Code Review & QA',
      body: 'Pull requests abiertos pendientes de validación',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['task-undo-redo'],
      side: 'bottom',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#047857',
      borderColor: '#86efac',
      borderWidth: 1.5,
      bold: true,
    },
    'task-undo-redo': {
      id: 'task-undo-redo',
      text: 'Historial Undo/Redo multicapa',
      body: 'Optimización del stack de estados con compresión de memoria',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-review',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      progress: 90,
      icons: ['check'],
      tags: ['Review', 'QA'],
    },
    'col-done': {
      id: 'col-done',
      text: '✅ Completado (Done)',
      body: 'Historias cerradas y probadas listas para producción',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['task-done-zoom', 'task-done-gaps'],
      side: 'bottom',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#047857',
      borderColor: '#86efac',
      borderWidth: 1.5,
      bold: true,
    },
    'task-done-zoom': {
      id: 'task-done-zoom',
      text: 'Zoom suave con rueda y gestos táctiles',
      body: 'Soporte fluido en trackpads y pantallas táctiles',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-done',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      progress: 100,
      icons: ['check'],
    },
    'task-done-gaps': {
      id: 'task-done-gaps',
      text: 'Control numérico de espaciado X/Y',
      body: 'Slidres y cajas de texto de separación horizontal y vertical',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-done',
      children: [],
      side: 'bottom',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      progress: 100,
      icons: ['check'],
    },
    'col-backlog': {
      id: 'col-backlog',
      text: '📋 Backlog Próximo Sprint',
      body: 'Historias priorizadas para el siguiente ciclo',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['task-auth-oauth'],
      side: 'top',
      shape: 'bubble',
      color: '#f0fdf4',
      textColor: '#047857',
      borderColor: '#86efac',
      borderWidth: 1.5,
      bold: true,
    },
    'task-auth-oauth': {
      id: 'task-auth-oauth',
      text: 'Autenticación P2P opcional',
      body: 'Integración WebRTC para edición colaborativa local',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'col-backlog',
      children: [],
      side: 'top',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#a7f3d0',
      borderWidth: 1.5,
      progress: 0,
      tags: ['Research'],
    },
  },
};

// ============================================================================
// 7. SÍNTESIS ACADÉMICA & ESTUDIO (Forks Clásicos / Curvas Spindle)
// ============================================================================
export const STUDY_EXAM_MAP: MindMap = {
  id: 'map-academic-study',
  title: 'Síntesis de Estudio: Neurociencia',
  rootId: 'root',
  layout: 'circular',
  themeId: 'default',
  edgeStyle: 'bezier',
  edgeProfile: 'spindle',
  edgeWidth: 2.6,
  edgeDash: 'solid',
  horizontalGap: 52,
  verticalGap: 12,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-study-1',
      fromId: 'cortex-prefrontal',
      toId: 'neuro-dopamina',
      label: 'Regulación de recompensa y foco',
      color: '#2563eb',
      style: 'solid',
      arrow: 'both',
    },
    {
      id: 'conn-study-2',
      fromId: 'mem-hipocampo',
      toId: 'mem-largo-plazo',
      label: 'Consolidación durante el sueño',
      color: '#7c3aed',
      style: 'dashed',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🧠 Bases de la Neurociencia',
      body: 'Estructuras cerebrales, sinapsis, memoria y neurotransmisores',
      bodyFontSize: 11,
      bodyColor: '#dbeafe',
      parentId: null,
      children: ['sec-anatomia', 'sec-neurotransmisores', 'sec-memoria', 'sec-plasticidad'],
      side: 'root',
      shape: 'bubble',
      color: '#1d4ed8',
      textColor: '#ffffff',
      bold: true,
      fontSize: 16,
      borderColor: '#3b82f6',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.educationCap,
      imagePosition: 'top',
      imageWidth: 64,
      tags: ['Neurociencia', 'Estudio'],
    },
    'sec-anatomia': {
      id: 'sec-anatomia',
      text: '1. Anatomía Cerebral',
      body: 'Divisiones funcionales del encéfalo humano',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['cortex-prefrontal', 'sis-limbico'],
      side: 'right',
      shape: 'fork',
      textColor: '#1e3a8a',
      bold: true,
      fontSize: 14,
    },
    'cortex-prefrontal': {
      id: 'cortex-prefrontal',
      text: 'Corteza Prefrontal',
      body: 'Funciones ejecutivas, toma de decisiones, autocontrol y planificación',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-anatomia',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#0f172a',
      note: '### Corteza Prefrontal\n- **Áreas de Brodmann**: 9, 10, 11, 46, 47\n- Principal sustrato de la memoria de trabajo',
    },
    'sis-limbico': {
      id: 'sis-limbico',
      text: 'Sistema Límbico',
      body: 'Amígdala (emociones e instinto de alerta) e Hipocampo',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-anatomia',
      children: ['mem-hipocampo'],
      side: 'right',
      shape: 'fork',
      textColor: '#0f172a',
    },
    'mem-hipocampo': {
      id: 'mem-hipocampo',
      text: 'Hipocampo & Giro Dentado',
      body: 'Conversión de recuerdos a corto plazo en memoria declarativa',
      bodyFontSize: 9.5,
      bodyColor: '#475569',
      parentId: 'sis-limbico',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#1e293b',
    },
    'sec-neurotransmisores': {
      id: 'sec-neurotransmisores',
      text: '2. Neurotransmisores Clave',
      body: 'Mensajeros químicos que modulan los impulsos nerviosos',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['neuro-dopamina', 'neuro-serotonina', 'neuro-gaba'],
      side: 'right',
      shape: 'fork',
      textColor: '#1e3a8a',
      bold: true,
      fontSize: 14,
    },
    'neuro-dopamina': {
      id: 'neuro-dopamina',
      text: 'Dopamina (Vía Mesolímbica)',
      body: 'Motivación, predicción de recompensa y control motor',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-neurotransmisores',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#0f172a',
      icons: ['sparkles'],
      tags: ['Dopamina', 'Recompensa'],
    },
    'neuro-serotonina': {
      id: 'neuro-serotonina',
      text: 'Serotonina (5-HT)',
      body: 'Regulación del estado de ánimo, sueño, apetito y ritmo circadiano',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-neurotransmisores',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#0f172a',
    },
    'neuro-gaba': {
      id: 'neuro-gaba',
      text: 'GABA & Glutamato',
      body: 'Equilibrio entre inhibición (GABA) y excitación (Glutamato)',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-neurotransmisores',
      children: [],
      side: 'right',
      shape: 'fork',
      textColor: '#0f172a',
    },
    'sec-memoria': {
      id: 'sec-memoria',
      text: '3. Tipos de Memoria',
      body: 'Clasificación temporal y funcional de la retención de datos',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['mem-corto-plazo', 'mem-largo-plazo'],
      side: 'left',
      shape: 'fork',
      textColor: '#1e3a8a',
      bold: true,
      fontSize: 14,
    },
    'mem-corto-plazo': {
      id: 'mem-corto-plazo',
      text: 'Memoria de Trabajo / Operativa',
      body: 'Capacidad de retención activa de 4 a 7 elementos concurrentes',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-memoria',
      children: [],
      side: 'left',
      shape: 'fork',
      textColor: '#0f172a',
    },
    'mem-largo-plazo': {
      id: 'mem-largo-plazo',
      text: 'Memoria a Largo Plazo',
      body: 'Explícita (semántica y episódica) e Implícita (procedimental)',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-memoria',
      children: [],
      side: 'left',
      shape: 'fork',
      textColor: '#0f172a',
      icons: ['bookmark'],
    },
    'sec-plasticidad': {
      id: 'sec-plasticidad',
      text: '4. Neuroplasticidad & Aprendizaje',
      body: 'Capacidad cerebral de reorganizar conexiones sinápticas',
      bodyFontSize: 10,
      bodyColor: '#1e40af',
      parentId: 'root',
      children: ['pl-hebb', 'pl-mielina'],
      side: 'left',
      shape: 'fork',
      textColor: '#1e3a8a',
      bold: true,
      fontSize: 14,
    },
    'pl-hebb': {
      id: 'pl-hebb',
      text: 'Ley de Hebb (LTP)',
      body: '"Las neuronas que disparan juntas, se conectan juntas" (Potenciación a Largo Plazo)',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-plasticidad',
      children: [],
      side: 'left',
      shape: 'fork',
      textColor: '#0f172a',
      icons: ['zap'],
      tags: ['LTP', 'Sinapsis'],
    },
    'pl-mielina': {
      id: 'pl-mielina',
      text: 'Mielinización & Práctica Deliberada',
      body: 'Aislamiento de axones para acelerar la velocidad de conducción del impulso',
      bodyFontSize: 9.5,
      bodyColor: '#334155',
      parentId: 'sec-plasticidad',
      children: [],
      side: 'left',
      shape: 'fork',
      textColor: '#1e293b',
    },
  },
};

// ============================================================================
// 8. EMBUDO DE MARKETING & GROWTH (Sunset / Líneas Rectas / Hexágonos)
// ============================================================================
export const MARKETING_FUNNEL_MAP: MindMap = {
  id: 'map-marketing-funnel',
  title: 'Embudo de Marketing & Conversión',
  rootId: 'root',
  layout: 'left',
  themeId: 'sunset',
  edgeStyle: 'linear',
  edgeProfile: 'hourglass',
  edgeWidth: 3.2,
  edgeDash: 'solid',
  horizontalGap: 75,
  verticalGap: 22,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-mkt-1',
      fromId: 'bofu-onboarding',
      toId: 'adv-referrals',
      label: 'Loop Viral de Recomendación',
      color: '#ea580c',
      style: 'dashed',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '📈 Embudo Growth & Ventas',
      body: 'Estrategia de adquisición multicanal, nutrición de prospectos y retención de usuarios',
      bodyFontSize: 11.5,
      bodyColor: '#ffedd5',
      parentId: null,
      children: ['stage-tofu', 'stage-mofu', 'stage-bofu', 'stage-advocacy'],
      side: 'root',
      shape: 'hexagon',
      color: '#ea580c',
      textColor: '#ffffff',
      bold: true,
      fontSize: 17,
      borderColor: '#c2410c',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.marketingTarget,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['target'],
      tags: ['Marketing', 'Embudo'],
    },
    'stage-tofu': {
      id: 'stage-tofu',
      text: '1. TOFU: Atracción & Conciencia',
      body: 'Generar tráfico cualificado y captar atención inicial',
      bodyFontSize: 10,
      bodyColor: '#7c2d12',
      parentId: 'root',
      children: ['tofu-seo', 'tofu-ads', 'tofu-social'],
      side: 'left',
      shape: 'rectangle',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#fb923c',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(251, 146, 60, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'tofu-seo': {
      id: 'tofu-seo',
      text: 'SEO & Marketing de Contenidos',
      body: 'Artículos de blog optimizados para palabras clave de alta intención',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-tofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'tofu-ads': {
      id: 'tofu-ads',
      text: 'Publicidad de Búsqueda (Google Ads)',
      body: 'Campañas dirigidas a usuarios que buscan alternativas a Mindomo/Freeplane',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-tofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'tofu-social': {
      id: 'tofu-social',
      text: 'Redes Sociales & Comunidad',
      body: 'Publicaciones visuales en Twitter, LinkedIn y YouTube Shorts',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-tofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'stage-mofu': {
      id: 'stage-mofu',
      text: '2. MOFU: Consideración & Interés',
      body: 'Educar sobre las ventajas diferenciales de la aplicación',
      bodyFontSize: 10,
      bodyColor: '#7c2d12',
      parentId: 'root',
      children: ['mofu-leadmagnet', 'mofu-webinar', 'mofu-templates'],
      side: 'left',
      shape: 'rectangle',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#fb923c',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(251, 146, 60, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'mofu-leadmagnet': {
      id: 'mofu-leadmagnet',
      text: 'Guía Gratuita: Técnicas Buzan Modernas',
      body: 'PDF descargable a cambio del correo electrónico',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-mofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      icons: ['book'],
    },
    'mofu-webinar': {
      id: 'mofu-webinar',
      text: 'Taller en Vivo: Productividad Visual',
      body: 'Demostración de flujos de trabajo rápidos sin ratón',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-mofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'mofu-templates': {
      id: 'mofu-templates',
      text: 'Galería de Plantillas Descargables',
      body: 'Colección de más de 20 mapas listos para usar',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-mofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'stage-bofu': {
      id: 'stage-bofu',
      text: '3. BOFU: Decisión & Conversión',
      body: 'Convertir prospectos en usuarios activos diarios',
      bodyFontSize: 10,
      bodyColor: '#7c2d12',
      parentId: 'root',
      children: ['bofu-trial', 'bofu-onboarding'],
      side: 'left',
      shape: 'rectangle',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#fb923c',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(251, 146, 60, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'bofu-trial': {
      id: 'bofu-trial',
      text: 'Demostración Interactiva Sin Registro',
      body: 'Probar el editor directamente en la web con 1 clic',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-bofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      icons: ['sparkles'],
    },
    'bofu-onboarding': {
      id: 'bofu-onboarding',
      text: 'Secuencia de Bienvenida Interactiva',
      body: 'Guía paso a paso para crear el primer mapa en menos de 2 minutos',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-bofu',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
    'stage-advocacy': {
      id: 'stage-advocacy',
      text: '4. Fidelización & Embajadores',
      body: 'Retención a largo plazo y recomendación boca a boca',
      bodyFontSize: 10,
      bodyColor: '#7c2d12',
      parentId: 'root',
      children: ['adv-referrals', 'adv-vip'],
      side: 'left',
      shape: 'rectangle',
      color: '#fff7ed',
      textColor: '#9a3412',
      borderColor: '#fb923c',
      borderWidth: 1.5,
      bold: true,
    },
    'adv-referrals': {
      id: 'adv-referrals',
      text: 'Programa de Recompensas por Invitación',
      body: 'Beneficios desbloqueables al invitar a colegas de trabajo',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-advocacy',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
      icons: ['trophy'],
    },
    'adv-vip': {
      id: 'adv-vip',
      text: 'Comunidad VIP de Creadores',
      body: 'Acceso anticipado a nuevas versiones y soporte prioritario',
      bodyFontSize: 9.5,
      bodyColor: '#9a3412',
      parentId: 'stage-advocacy',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#c2410c',
      borderColor: '#fdba74',
      borderWidth: 1.5,
    },
  },
};

// ============================================================================
// 9. ÁRBOL DE DECISIÓN & CAUSA RAÍZ (Dark Mode / Sharp / Tapered)
// ============================================================================
export const DECISION_TREE_MAP: MindMap = {
  id: 'map-decision-tree-rca',
  title: 'Árbol de Decisión & Causa Raíz',
  rootId: 'root',
  layout: 'right',
  themeId: 'dark',
  edgeStyle: 'sharp',
  edgeProfile: 'tapered',
  edgeWidth: 2.5,
  edgeDash: 'dashed',
  horizontalGap: 90,
  verticalGap: 14,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-rca-1',
      fromId: 'cause-infra-scale',
      toId: 'sol-auto-scale',
      label: 'Acción Correctiva Principal',
      color: '#34d399',
      style: 'solid',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '⚠️ Incidente: Alta Latencia API',
      body: 'Análisis Causa-Raíz (5 Porqués) para resolver picos de lentitud en producción',
      bodyFontSize: 11,
      bodyColor: '#fecdd3',
      parentId: null,
      children: ['branch-db', 'branch-infra', 'branch-code'],
      side: 'root',
      shape: 'hexagon',
      color: '#9f1239',
      textColor: '#ffffff',
      bold: true,
      fontSize: 16,
      borderColor: '#f43f5e',
      borderWidth: 2,
      imageUrl: TEMPLATE_SVGS.bugFix,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['alert'],
      tags: ['Incidencia', 'RCA'],
    },
    'branch-db': {
      id: 'branch-db',
      text: '1. ¿Sobrecarga en Base de Datos?',
      body: 'Consultas lentas y saturación del pool de conexiones',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['cause-missing-index', 'sol-add-index'],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#f43f5e',
      borderColor: '#881337',
      borderWidth: 1.5,
      bold: true,
    },
    'cause-missing-index': {
      id: 'cause-missing-index',
      text: 'Causa: Consulta compleja sin índice en tabla orders',
      body: 'Escaneo secuencial completo de 2 millones de filas por petición',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'branch-db',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#fda4af',
      borderColor: '#e11d48',
      borderWidth: 1,
    },
    'sol-add-index': {
      id: 'sol-add-index',
      text: 'Solución: Índice Compuesto (user_id, created_at)',
      body: 'Tiempo de consulta reducido de 850ms a 4ms',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'branch-db',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#4ade80',
      borderColor: '#16a34a',
      borderWidth: 1,
      icons: ['check'],
    },
    'branch-infra': {
      id: 'branch-infra',
      text: '2. ¿Límite de Recursos en Pods?',
      body: 'CPU throttling en Kubernetes durante horas pico',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['cause-infra-scale', 'sol-auto-scale'],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#fbbf24',
      borderColor: '#78350f',
      borderWidth: 1.5,
      bold: true,
    },
    'cause-infra-scale': {
      id: 'cause-infra-scale',
      text: 'Causa: HPA configurado con umbral de réplica muy alto (90%)',
      body: 'Los pods nuevos tardaban 2 minutos en responder a ráfagas de tráfico',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'branch-infra',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#fde68a',
      borderColor: '#d97706',
      borderWidth: 1,
    },
    'sol-auto-scale': {
      id: 'sol-auto-scale',
      text: 'Solución: HPA a 65% CPU + KEDA con métricas de cola',
      body: 'Escalado anticipado basado en el número de solicitudes en cola',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'branch-infra',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#4ade80',
      borderColor: '#16a34a',
      borderWidth: 1,
      icons: ['check'],
    },
    'branch-code': {
      id: 'branch-code',
      text: '3. ¿Fugas de Memoria en Código?',
      body: 'Consumo continuo y recolección de basura bloqueante',
      bodyFontSize: 10,
      bodyColor: '#cbd5e1',
      parentId: 'root',
      children: ['sol-cache-cleanup'],
      side: 'right',
      shape: 'rectangle',
      color: '#1e293b',
      textColor: '#60a5fa',
      borderColor: '#1e3a8a',
      borderWidth: 1.5,
      bold: true,
    },
    'sol-cache-cleanup': {
      id: 'sol-cache-cleanup',
      text: 'Verificado: Heap estable con LRU Cache acotada',
      body: 'No se detectaron fugas de memoria en el profiling de V8',
      bodyFontSize: 9.5,
      bodyColor: '#94a3b8',
      parentId: 'branch-code',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#0f172a',
      textColor: '#93c5fd',
      borderColor: '#2563eb',
      borderWidth: 1,
      icons: ['check'],
    },
  },
};

// ============================================================================
// 10. PLAN DE LANZAMIENTO PRODUCTO & GTM (Forest / Nubes / Conectores)
// ============================================================================
export const PRODUCT_GTM_MAP: MindMap = {
  id: 'map-product-gtm-launch',
  title: 'Plan de Lanzamiento & Go-To-Market',
  rootId: 'root',
  layout: 'bottom',
  themeId: 'forest',
  edgeStyle: 'bezier',
  edgeProfile: 'uniform',
  edgeWidth: 3.2,
  edgeDash: 'solid',
  horizontalGap: 62,
  verticalGap: 18,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [
    {
      id: 'conn-gtm-1',
      fromId: 'gtm-press-kit',
      toId: 'gtm-product-hunt',
      label: 'Kit para difusores en Product Hunt',
      color: '#059669',
      style: 'dashed',
      arrow: 'end',
    },
    {
      id: 'conn-gtm-2',
      fromId: 'gtm-qa-audit',
      toId: 'gtm-deploy-prod',
      label: 'Aprobación obligatoria',
      color: '#047857',
      style: 'solid',
      arrow: 'end',
    },
  ],
  nodes: {
    root: {
      id: 'root',
      text: '🚀 Lanzamiento Oficial v2.0',
      body: 'Campaña global Go-To-Market: Producto, Prensa, Comunidad y Soporte',
      bodyFontSize: 11.5,
      bodyColor: '#d1fae5',
      parentId: null,
      children: ['phase-pre', 'phase-launch', 'phase-post', 'phase-metrics'],
      side: 'root',
      shape: 'bubble',
      color: '#064e3b',
      textColor: '#ffffff',
      bold: true,
      fontSize: 17,
      borderColor: '#10b981',
      borderWidth: 2,
      progress: 62,
      imageUrl: TEMPLATE_SVGS.rocketLaunch,
      imagePosition: 'top',
      imageWidth: 64,
      icons: ['rocket'],
      tags: ['Lanzamiento', 'v2.0'],
    },
    'phase-pre': {
      id: 'phase-pre',
      text: '1. Pre-Lanzamiento (T-15 días)',
      body: 'Preparación de materiales, beta privada y auditoría final',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['gtm-beta-testers', 'gtm-press-kit', 'gtm-qa-audit'],
      side: 'left',
      shape: 'bubble',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(5, 150, 105, 0.08)',
        shape: 'round-rectangle',
      },
    },
    'gtm-beta-testers': {
      id: 'gtm-beta-testers',
      text: 'Feedback de 100 Beta Testers VIP',
      body: 'Resolución de fricciones y testimonios de uso real',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-pre',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 100,
      icons: ['check'],
    },
    'gtm-press-kit': {
      id: 'gtm-press-kit',
      text: 'Kit de Prensa & Capturas HD',
      body: 'Logos vectoriales, notas de prensa y videos de demostración',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-pre',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 85,
    },
    'gtm-qa-audit': {
      id: 'gtm-qa-audit',
      text: 'Auditoría de Rendimiento & Accesibilidad',
      body: 'Validación Lighthouse 100/100 en desktop y mobile',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-pre',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 100,
      icons: ['check'],
    },
    'phase-launch': {
      id: 'phase-launch',
      text: '2. Día del Lanzamiento (Día D)',
      body: 'Despliegue a producción y activación de canales',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['gtm-deploy-prod', 'gtm-product-hunt', 'gtm-social-blast'],
      side: 'right',
      shape: 'bubble',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
      borderWidth: 1.5,
      bold: true,
      cloud: {
        enabled: true,
        color: 'rgba(16, 185, 129, 0.08)',
        shape: 'arc',
      },
    },
    'gtm-deploy-prod': {
      id: 'gtm-deploy-prod',
      text: 'Despliegue Global Cloud Run & CDN',
      body: 'Publicación de la versión final sin interrupción de servicio',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-launch',
      children: [],
      side: 'right',
      shape: 'hexagon',
      color: '#ffffff',
      textColor: '#047857',
      borderColor: '#10b981',
      borderWidth: 1.5,
      progress: 100,
      icons: ['check'],
    },
    'gtm-product-hunt': {
      id: 'gtm-product-hunt',
      text: 'Lanzamiento en Product Hunt',
      body: 'Meta: Top 3 Producto del Día',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-launch',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 40,
      icons: ['trophy'],
    },
    'gtm-social-blast': {
      id: 'gtm-social-blast',
      text: 'Anuncio en X, LinkedIn y Reddit',
      body: 'Hilo explicativo con demo interactiva embebida',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-launch',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 50,
    },
    'phase-post': {
      id: 'phase-post',
      text: '3. Post-Lanzamiento (T+15 días)',
      body: 'Soporte activo, recopilación de feedback y parches rápidos',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['gtm-support-war', 'gtm-patch-release'],
      side: 'right',
      shape: 'bubble',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
      borderWidth: 1.5,
      bold: true,
    },
    'gtm-support-war': {
      id: 'gtm-support-war',
      text: 'War Room de Soporte en Vivo',
      body: 'Respuesta en menos de 15 minutos a dudas y reportes',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-post',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 30,
    },
    'gtm-patch-release': {
      id: 'gtm-patch-release',
      text: 'Release v2.0.1 (Minor Fixes)',
      body: 'Solución a pequeños detalles reportados por los primeros usuarios',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-post',
      children: [],
      side: 'right',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 10,
    },
    'phase-metrics': {
      id: 'phase-metrics',
      text: '4. Métricas de Éxito',
      body: 'KPIs cuantitativos de adopción y retención',
      bodyFontSize: 10,
      bodyColor: '#064e3b',
      parentId: 'root',
      children: ['gtm-kpi-users', 'gtm-kpi-export'],
      side: 'left',
      shape: 'bubble',
      color: '#ecfdf5',
      textColor: '#047857',
      borderColor: '#34d399',
      borderWidth: 1.5,
      bold: true,
    },
    'gtm-kpi-users': {
      id: 'gtm-kpi-users',
      text: '10,000 Usuarios Activos Semanales',
      body: 'Medición de mapas creados y guardados localmente',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-metrics',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 55,
      icons: ['target'],
    },
    'gtm-kpi-export': {
      id: 'gtm-kpi-export',
      text: '> 50,000 Archivos .mm & HTML Exportados',
      body: 'Indicador clave de utilidad práctica y valor para el usuario',
      bodyFontSize: 9.5,
      bodyColor: '#064e3b',
      parentId: 'phase-metrics',
      children: [],
      side: 'left',
      shape: 'pill',
      color: '#ffffff',
      textColor: '#059669',
      borderColor: '#6ee7b7',
      borderWidth: 1.5,
      progress: 40,
    },
  },
};

// ============================================================================
// MAPA EN BLANCO BÁSICO
// ============================================================================
export const BLANK_MAP: MindMap = {
  id: 'map-new',
  title: 'Nuevo Mapa Mental',
  rootId: 'root',
  layout: 'standard',
  themeId: 'default',
  edgeStyle: 'bezier',
  edgeProfile: 'uniform',
  edgeWidth: 2.5,
  edgeDash: 'solid',
  horizontalGap: 54,
  verticalGap: 14,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  connectors: [],
  nodes: {
    root: {
      id: 'root',
      text: 'Idea Central',
      body: 'Tema principal de tu mapa mental. Puedes editar el título y esta explicación desde el panel de propiedades (Alt+P) o con doble clic.',
      bodyFontSize: 11,
      bodyColor: '#bfdbfe',
      parentId: null,
      children: ['node-1', 'node-2'],
      side: 'root',
      shape: 'bubble',
      color: '#2563eb',
      textColor: '#ffffff',
      bold: true,
      fontSize: 16,
    },
    'node-1': {
      id: 'node-1',
      text: 'Rama Principal 1',
      body: 'Concepto o subtema. Presiona TAB para añadir un nodo hijo o ENTER para un hermano.',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'right',
      shape: 'bubble',
      color: '#f8fafc',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
      borderWidth: 1.5,
    },
    'node-2': {
      id: 'node-2',
      text: 'Rama Principal 2',
      body: 'Detalle adicional. Personaliza colores, formas geométricas y notas desde el panel de propiedades.',
      bodyFontSize: 10,
      bodyColor: '#475569',
      parentId: 'root',
      children: [],
      side: 'left',
      shape: 'bubble',
      color: '#f8fafc',
      textColor: '#1e293b',
      borderColor: '#93c5fd',
      borderWidth: 1.5,
    },
  },
};

// ============================================================================
// COLECCIÓN COMPLETA DE LAS 20 PLANTILLAS
// ============================================================================
export const ALL_TEMPLATES = [
  {
    map: TUTORIAL_MAP,
    id: 'tutorial',
    title: 'Guía Interactiva & Tutorial Completo',
    category: 'Destacada',
    desc: 'Aprende todas las funciones con atajos de teclado, conectores, notas Markdown y exportaciones.',
    themeName: 'Clásico Azul',
    layoutLabel: 'Bilateral Clásico',
    edgeDesc: 'Curva Cónica (Buzan)',
    tags: ['Atajos', 'Markdown', 'Tutorial'],
    color: 'border-blue-200 bg-blue-50/50 hover:border-blue-400',
    badgeColor: 'bg-blue-100 text-blue-800',
  },
  {
    map: OKR_STRATEGY_MAP,
    id: 'okr-strategy',
    title: 'Planificación Estratégica & OKRs 2026',
    category: 'Estrategia',
    desc: 'Estructura en árbol horizontal con ángulos rectos, perfiles de huso, métricas y barras de progreso.',
    themeName: 'Atardecer Cálido',
    layoutLabel: 'Árbol Derecha',
    edgeDesc: 'Ángulo Recto (Huso)',
    tags: ['OKRs', 'Progreso', 'Estrategia'],
    color: 'border-amber-200 bg-amber-50/50 hover:border-amber-400',
    badgeColor: 'bg-amber-100 text-amber-800',
  },
  {
    map: CLOUD_ARCH_MAP,
    id: 'cloud-arch',
    title: 'Arquitectura Cloud & Microservicios',
    category: 'Tecnología',
    desc: 'Diagrama técnico radial de 360° en modo oscuro con hexágonos, líneas discontinuas y eventos Pub/Sub.',
    themeName: 'Modo Oscuro',
    layoutLabel: 'Radial 360°',
    edgeDesc: 'Línea Discontinua',
    tags: ['DevOps', 'Cloud', 'Microservicios'],
    color: 'border-slate-700 bg-slate-900/90 text-slate-100 hover:border-sky-500',
    badgeColor: 'bg-slate-800 text-sky-400 border border-slate-700',
  },
  {
    map: BRAINSTORMING_MAP,
    id: 'brainstorming',
    title: 'Brainstorming Creativo & Innovación',
    category: 'Creatividad',
    desc: 'Lluvia de ideas multicolor con curvas amplias de reloj de arena, nubes y tags de votación.',
    themeName: 'Arcoíris Vibrante',
    layoutLabel: 'Bilateral Fluido',
    edgeDesc: 'Curva en Reloj de Arena',
    tags: ['Creatividad', 'Multicolor', 'Ideas'],
    color: 'border-pink-200 bg-pink-50/50 hover:border-pink-400',
    badgeColor: 'bg-pink-100 text-pink-800',
  },
  {
    map: ORG_CHART_MAP,
    id: 'org-chart',
    title: 'Organigrama y Estructura Corporativa',
    category: 'Estrategia',
    desc: 'Jerarquía empresarial monocromática descendente (Top-Down) con tarjetas estructuradas.',
    themeName: 'Minimalista Mono',
    layoutLabel: 'Organigrama Descendente',
    edgeDesc: 'Ángulo Recto Fino',
    tags: ['Organigrama', 'Equipo', 'Minimal'],
    color: 'border-zinc-200 bg-zinc-50/60 hover:border-zinc-400',
    badgeColor: 'bg-zinc-200 text-zinc-800',
  },
  {
    map: AGILE_SPRINT_MAP,
    id: 'agile-sprint',
    title: 'Tablero Sprint Scrum & Backlog Ágil',
    category: 'Gestión',
    desc: 'Seguimiento ágil en tono esmeralda con distribución equilibrada horizontal (arriba y abajo).',
    themeName: 'Bosque Esmeralda',
    layoutLabel: 'Equilibrado Arriba/Abajo',
    edgeDesc: 'Punteado Cónico',
    tags: ['Scrum', 'Sprint', 'Píldoras'],
    color: 'border-emerald-200 bg-emerald-50/50 hover:border-emerald-400',
    badgeColor: 'bg-emerald-100 text-emerald-800',
  },
  {
    map: STUDY_EXAM_MAP,
    id: 'study-exam',
    title: 'Síntesis de Estudio & Preparación de Examen',
    category: 'Educación',
    desc: 'Toma de apuntes en anillos concéntricos alrededor del concepto central de Neurociencia.',
    themeName: 'Clásico Azul',
    layoutLabel: 'Circular Concéntrico',
    edgeDesc: 'Curva Ancha al Medio',
    tags: ['Estudio', 'Horquillas', 'Examen'],
    color: 'border-blue-200 bg-blue-50/40 hover:border-blue-400',
    badgeColor: 'bg-blue-100 text-blue-800',
  },
  {
    map: MARKETING_FUNNEL_MAP,
    id: 'marketing-funnel',
    title: 'Embudo de Marketing & Growth Hacking',
    category: 'Estrategia',
    desc: 'Etapas de adquisición TOFU/MOFU/BOFU extendiéndose unilateralmente hacia la izquierda.',
    themeName: 'Atardecer Cálido',
    layoutLabel: 'Árbol Izquierda',
    edgeDesc: 'Línea Reloj de Arena',
    tags: ['Marketing', 'Embudo', 'Ventas'],
    color: 'border-orange-200 bg-orange-50/50 hover:border-orange-400',
    badgeColor: 'bg-orange-100 text-orange-800',
  },
  {
    map: DECISION_TREE_MAP,
    id: 'decision-tree',
    title: 'Árbol de Decisión & Causa Raíz (RCA)',
    category: 'Tecnología',
    desc: 'Resolución de problemas técnicos con bifurcaciones en ángulo extendiéndose a la derecha.',
    themeName: 'Modo Oscuro',
    layoutLabel: 'Árbol Derecha',
    edgeDesc: 'Ángulo Discontinuo',
    tags: ['Causa-Raíz', 'Incidencias', 'Decisión'],
    color: 'border-slate-700 bg-slate-900/90 text-slate-100 hover:border-rose-500',
    badgeColor: 'bg-slate-800 text-rose-400 border border-slate-700',
  },
  {
    map: PRODUCT_GTM_MAP,
    id: 'product-gtm',
    title: 'Plan de Lanzamiento & Go-To-Market (GTM)',
    category: 'Gestión',
    desc: 'Cronograma y fases de lanzamiento organizadas en cascada vertical descendente.',
    themeName: 'Bosque Esmeralda',
    layoutLabel: 'Cronograma Descendente',
    edgeDesc: 'Curva Continua Fuerte',
    tags: ['Lanzamiento', 'GTM', 'Hitos'],
    color: 'border-teal-200 bg-teal-50/50 hover:border-teal-400',
    badgeColor: 'bg-teal-100 text-teal-800',
  },
  // --- 10 NUEVAS PLANTILLAS ENRIQUECIDAS ---
  {
    map: AI_PRODUCT_ROADMAP_MAP,
    id: 'ai-roadmap',
    title: 'Roadmap de Producto IA Generativa & Agentes',
    category: 'Tecnología',
    desc: 'Ecosistema de modelos LLM/SLM, agentes autónomos, pipelines RAG híbridos y seguridad en disposición radial.',
    themeName: 'Modo Oscuro',
    layoutLabel: 'Radial Multi-Agente',
    edgeDesc: 'Curva Bézier Cónica',
    tags: ['IA', 'GenAI', 'Agentes', 'LLM'],
    color: 'border-sky-500/50 bg-slate-900/90 text-slate-100 hover:border-sky-400',
    badgeColor: 'bg-sky-950 text-sky-400 border border-sky-800',
  },
  {
    map: SWOT_ANALYSIS_MAP,
    id: 'swot-matrix',
    title: 'Matriz Estratégica FODA / DAFO Corporativa',
    category: 'Estrategia',
    desc: 'Diagnóstico 360° con 4 cuadrantes balanceados a izquierda y derecha con conectores de acción.',
    themeName: 'Arcoíris Vibrante',
    layoutLabel: 'Bilateral 4 Cuadrantes',
    edgeDesc: 'Curva Fluida Multitono',
    tags: ['FODA', 'DAFO', 'Estrategia', 'Diagnóstico'],
    color: 'border-blue-200 bg-blue-50/50 hover:border-blue-400',
    badgeColor: 'bg-blue-100 text-blue-800',
  },
  {
    map: CYBERSECURITY_FRAMEWORK_MAP,
    id: 'cybersecurity-framework',
    title: 'Marco de Ciberseguridad NIST & Zero-Trust',
    category: 'Tecnología',
    desc: 'Los 5 pilares NIST (Identificar, Proteger, Detectar, Responder, Recuperar) en cascada descendente.',
    themeName: 'Modo Oscuro',
    layoutLabel: 'Organigrama Descendente',
    edgeDesc: 'Ángulo Recto Estricto',
    tags: ['Ciberseguridad', 'NIST', 'ZeroTrust', 'SOC'],
    color: 'border-indigo-500/50 bg-slate-900/90 text-slate-100 hover:border-indigo-400',
    badgeColor: 'bg-indigo-950 text-indigo-300 border border-indigo-800',
  },
  {
    map: CUSTOMER_JOURNEY_MAP,
    id: 'customer-journey',
    title: 'Mapa de Experiencia de Cliente (Customer Journey & UX)',
    category: 'Gestión',
    desc: 'De descubrimiento a retención en un flujo cronológico lineal extendido a la derecha.',
    themeName: 'Atardecer Cálido',
    layoutLabel: 'Flujo Lineal Derecha',
    edgeDesc: 'Curva en Reloj de Arena',
    tags: ['CustomerJourney', 'UX', 'Fidelización', 'NPS'],
    color: 'border-orange-200 bg-orange-50/50 hover:border-orange-400',
    badgeColor: 'bg-orange-100 text-orange-800',
  },
  {
    map: STARTUP_PITCH_DECK_MAP,
    id: 'startup-pitch',
    title: 'Estructura Maestra de Pitch Deck para Inversores',
    category: 'Estrategia',
    desc: 'Estructura de 10 diapositivas que asciende jerárquicamente desde el problema base hasta la ronda final.',
    themeName: 'Clásico Azul',
    layoutLabel: 'Jerarquía Ascendente',
    edgeDesc: 'Curva Cónica Sólida',
    tags: ['PitchDeck', 'Startup', 'Inversión', 'VC'],
    color: 'border-blue-200 bg-blue-50/50 hover:border-blue-400',
    badgeColor: 'bg-blue-100 text-blue-800',
  },
  {
    map: FULLSTACK_DEV_ROADMAP_MAP,
    id: 'fullstack-roadmap',
    title: 'Ruta Desarrollador Fullstack & DevOps 2026',
    category: 'Educación',
    desc: 'Escalera de habilidades profesionales construida verticalmente de abajo hacia arriba.',
    themeName: 'Modo Oscuro',
    layoutLabel: 'Ruta Ascendente',
    edgeDesc: 'Curva Bézier Fluida',
    tags: ['Fullstack', 'DevOps', 'NextJS', 'TypeScript'],
    color: 'border-cyan-500/50 bg-slate-900/90 text-slate-100 hover:border-cyan-400',
    badgeColor: 'bg-cyan-950 text-cyan-300 border border-cyan-800',
  },
  {
    map: FINANCIAL_BUDGET_MAP,
    id: 'financial-budget',
    title: 'Plan Financiero Corporativo, Presupuesto & Cash Flow',
    category: 'Gestión',
    desc: 'Desglose financiero equilibrado: Ingresos y Cash Flow arriba, Gastos OPEX y CAPEX abajo.',
    themeName: 'Bosque Esmeralda',
    layoutLabel: 'Equilibrado Arriba/Abajo',
    edgeDesc: 'Curva Suave Esmeralda',
    tags: ['Finanzas', 'Presupuesto', 'OPEX', 'CashFlow'],
    color: 'border-emerald-200 bg-emerald-50/50 hover:border-emerald-400',
    badgeColor: 'bg-emerald-100 text-emerald-800',
  },
  {
    map: DESIGN_SYSTEM_MAP,
    id: 'design-system',
    title: 'Sistema de Diseño UI/UX & Tokens de Componentes',
    category: 'Creatividad',
    desc: 'Tokens, átomos, componentes y patrones organizados alrededor del núcleo de diseño en 360°.',
    themeName: 'Arcoíris Vibrante',
    layoutLabel: 'Radial Núcleo Diseño',
    edgeDesc: 'Curva en Reloj de Arena',
    tags: ['DesignSystem', 'UI/UX', 'Tokens', 'Figma'],
    color: 'border-fuchsia-200 bg-fuchsia-50/50 hover:border-fuchsia-400',
    badgeColor: 'bg-fuchsia-100 text-fuchsia-800',
  },
  {
    map: CONTENT_CREATOR_SYSTEM_MAP,
    id: 'content-creator',
    title: 'Sistema de Creación de Contenido Multimedia & Redes',
    category: 'Creatividad',
    desc: 'Máquina de distribución omnicanal organizada en capas concéntricas desde la idea matriz.',
    themeName: 'Atardecer Cálido',
    layoutLabel: 'Circular por Capas',
    edgeDesc: 'Curva Cónica Dinámica',
    tags: ['Contenido', 'YouTube', 'Podcast', 'Monetización'],
    color: 'border-amber-200 bg-amber-50/50 hover:border-amber-400',
    badgeColor: 'bg-amber-100 text-amber-800',
  },
  {
    map: HEALTH_WELLNESS_MAP,
    id: 'health-wellness',
    title: 'Plan Integral de Salud, Hábitos & Biohacking',
    category: 'Educación',
    desc: 'Esferas concéntricas de salud (Sueño, Nutrición, Ejercicio, Mente) orbitando el núcleo vital.',
    themeName: 'Bosque Esmeralda',
    layoutLabel: 'Circular Concéntrico',
    edgeDesc: 'Curva Cónica Orgánica',
    tags: ['Salud', 'Biohacking', 'Hábitos', 'Bienestar'],
    color: 'border-emerald-200 bg-emerald-50/50 hover:border-emerald-400',
    badgeColor: 'bg-emerald-100 text-emerald-800',
  },
];
