import { MindMapTheme, BackgroundPatternStyle, MapBackgroundConfig } from '../types/mindmap';

export interface BackgroundPresetTheme {
  id: string;
  name: string;
  category: 'light' | 'dark' | 'paper' | 'technical' | 'creative';
  backgroundColor: string;
  pattern: BackgroundPatternStyle;
  patternColor: string;
  patternSize: number;
  patternOpacity: number;
  description: string;
}

export const THEMES: Record<string, MindMapTheme> = {
  default: {
    id: 'default',
    name: 'Clásico Azul',
    background: '#f8fafc',
    backgroundPattern: 'dots',
    backgroundPatternColor: '#94a3b8',
    backgroundPatternSize: 24,
    backgroundPatternOpacity: 0.45,
    rootBg: '#2563eb',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#1e293b',
    nodeBorder: '#cbd5e1',
    branchColors: ['#3b82f6', '#10b981', '#8b5cf6', '#f59e0b', '#ec4899', '#06b6d4', '#14b8a6'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
  rainbow: {
    id: 'rainbow',
    name: 'Arcoíris Vibrante',
    background: '#ffffff',
    backgroundPattern: 'squares',
    backgroundPatternColor: '#e2e8f0',
    backgroundPatternSize: 28,
    backgroundPatternOpacity: 0.6,
    rootBg: '#0f172a',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#0f172a',
    nodeBorder: '#e2e8f0',
    branchColors: ['#ef4444', '#f97316', '#f59e0b', '#10b981', '#06b6d4', '#3b82f6', '#8b5cf6', '#d946ef'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
  dark: {
    id: 'dark',
    name: 'Modo Oscuro',
    background: '#0f172a',
    backgroundPattern: 'dots',
    backgroundPatternColor: '#475569',
    backgroundPatternSize: 24,
    backgroundPatternOpacity: 0.5,
    rootBg: '#3b82f6',
    rootText: '#ffffff',
    nodeBg: '#1e293b',
    nodeText: '#f1f5f9',
    nodeBorder: '#334155',
    branchColors: ['#60a5fa', '#34d399', '#a78bfa', '#fbbf24', '#f472b6', '#38bdf8'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
  forest: {
    id: 'forest',
    name: 'Bosque Esmeralda',
    background: '#f0fdf4',
    backgroundPattern: 'dots',
    backgroundPatternColor: '#86efac',
    backgroundPatternSize: 24,
    backgroundPatternOpacity: 0.55,
    rootBg: '#047857',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#064e3b',
    nodeBorder: '#a7f3d0',
    branchColors: ['#059669', '#10b981', '#34d399', '#0d9488', '#14b8a6', '#84cc16'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
  sunset: {
    id: 'sunset',
    name: 'Atardecer Cálido',
    background: '#fffbeb',
    backgroundPattern: 'triangles',
    backgroundPatternColor: '#fed7aa',
    backgroundPatternSize: 32,
    backgroundPatternOpacity: 0.6,
    rootBg: '#ea580c',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#431407',
    nodeBorder: '#fed7aa',
    branchColors: ['#ea580c', '#f97316', '#fb923c', '#e11d48', '#f43f5e', '#d97706'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimalista Mono',
    background: '#fafafa',
    backgroundPattern: 'none',
    backgroundPatternColor: '#e4e4e7',
    backgroundPatternSize: 24,
    backgroundPatternOpacity: 0.4,
    rootBg: '#18181b',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#18181b',
    nodeBorder: '#e4e4e7',
    branchColors: ['#3f3f46', '#52525b', '#71717a', '#a1a1aa'],
    edgeStyle: 'linear',
    fontFamily: 'Plus Jakarta Sans',
  },
  blueprint: {
    id: 'blueprint',
    name: 'Plano Técnico Blueprint',
    background: '#0a2540',
    backgroundPattern: 'squares',
    backgroundPatternColor: '#0284c7',
    backgroundPatternSize: 28,
    backgroundPatternOpacity: 0.4,
    rootBg: '#0284c7',
    rootText: '#ffffff',
    nodeBg: '#0f3863',
    nodeText: '#f0f9ff',
    nodeBorder: '#0369a1',
    branchColors: ['#38bdf8', '#7dd3fc', '#bae6fd', '#67e8f9', '#a5f3fc'],
    edgeStyle: 'sharp',
    fontFamily: 'Plus Jakarta Sans',
  },
  honeycomb: {
    id: 'honeycomb',
    name: 'Panal Creativo',
    background: '#fffdf5',
    backgroundPattern: 'hexagons',
    backgroundPatternColor: '#fde68a',
    backgroundPatternSize: 32,
    backgroundPatternOpacity: 0.7,
    rootBg: '#d97706',
    rootText: '#ffffff',
    nodeBg: '#ffffff',
    nodeText: '#78350f',
    nodeBorder: '#fde68a',
    branchColors: ['#d97706', '#f59e0b', '#b45309', '#e11d48', '#ca8a04'],
    edgeStyle: 'bezier',
    fontFamily: 'Plus Jakarta Sans',
  },
};

/**
 * Curated background themes and preset styles specifically for the canvas background
 */
export const BACKGROUND_PRESET_THEMES: BackgroundPresetTheme[] = [
  {
    id: 'bg-clean-white',
    name: 'Lienzo Puro (Liso)',
    category: 'light',
    backgroundColor: '#ffffff',
    pattern: 'none',
    patternColor: '#cbd5e1',
    patternSize: 24,
    patternOpacity: 0.3,
    description: 'Fondo blanco minimalista sin trama para máxima concentración',
  },
  {
    id: 'bg-dot-grid-slate',
    name: 'Cuaderno de Puntos',
    category: 'paper',
    backgroundColor: '#fafaf9',
    pattern: 'dots',
    patternColor: '#78716c',
    patternSize: 24,
    patternOpacity: 0.4,
    description: 'Puntos estilo bullet journal sobre papel crema',
  },
  {
    id: 'bg-square-grid',
    name: 'Papel Milimetrado',
    category: 'technical',
    backgroundColor: '#f8fafc',
    pattern: 'squares',
    patternColor: '#94a3b8',
    patternSize: 24,
    patternOpacity: 0.45,
    description: 'Cuadrícula precisa para alineación geométrica',
  },
  {
    id: 'bg-blueprint-pro',
    name: 'Blueprint Técnico',
    category: 'technical',
    backgroundColor: '#0c2d48',
    pattern: 'squares',
    patternColor: '#38bdf8',
    patternSize: 28,
    patternOpacity: 0.35,
    description: 'Cuadrícula técnica azul eléctrico tipo cianotipo de ingeniería',
  },
  {
    id: 'bg-honeycomb-gold',
    name: 'Panal Hexagonal',
    category: 'creative',
    backgroundColor: '#fffdf5',
    pattern: 'hexagons',
    patternColor: '#d97706',
    patternSize: 32,
    patternOpacity: 0.4,
    description: 'Trama de hexágonos dorados interconectados',
  },
  {
    id: 'bg-triangular-mesh',
    name: 'Malla Triangular Isométrica',
    category: 'creative',
    backgroundColor: '#f1f5f9',
    pattern: 'triangles',
    patternColor: '#64748b',
    patternSize: 32,
    patternOpacity: 0.35,
    description: 'Estructura poligonal de triángulos equiláteros',
  },
  {
    id: 'bg-lined-paper',
    name: 'Rayas de Cuaderno',
    category: 'paper',
    backgroundColor: '#fafaf9',
    pattern: 'lines',
    patternColor: '#94a3b8',
    patternSize: 24,
    patternOpacity: 0.45,
    description: 'Líneas horizontales continuas para redacción ordenada',
  },
  {
    id: 'bg-dark-matrix-dots',
    name: 'Pizarra Oscura Puntos',
    category: 'dark',
    backgroundColor: '#0f172a',
    pattern: 'dots',
    patternColor: '#475569',
    patternSize: 24,
    patternOpacity: 0.6,
    description: 'Puntos sutiles sobre lienzo azul noche de alto contraste',
  },
  {
    id: 'bg-dark-honeycomb',
    name: 'Cyber Panal Oscuro',
    category: 'dark',
    backgroundColor: '#090d16',
    pattern: 'hexagons',
    patternColor: '#06b6d4',
    patternSize: 36,
    patternOpacity: 0.35,
    description: 'Hexágonos cian sobre fondo de grafito espacial',
  },
  {
    id: 'bg-dark-isometric',
    name: 'Malla Neón Triangular',
    category: 'dark',
    backgroundColor: '#111827',
    pattern: 'triangles',
    patternColor: '#8b5cf6',
    patternSize: 36,
    patternOpacity: 0.35,
    description: 'Triángulos en púrpura eléctrico en entorno oscuro',
  },
  {
    id: 'bg-graphite-lines',
    name: 'Grafito con Rayas',
    category: 'dark',
    backgroundColor: '#18181b',
    pattern: 'lines',
    patternColor: '#3f3f46',
    patternSize: 28,
    patternOpacity: 0.6,
    description: 'Líneas horizontales en tono grafito mate profesional',
  },
  {
    id: 'bg-mint-breeze',
    name: 'Brisa de Menta (Puntos)',
    category: 'light',
    backgroundColor: '#f0fdf4',
    pattern: 'dots',
    patternColor: '#22c55e',
    patternSize: 24,
    patternOpacity: 0.45,
    description: 'Atmósfera fresca y relajante en verde menta suave',
  },
];

